-- Outsourced items per valve/job + Vendor lookup category.
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.valve_outsourced_items (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  status text not null default 'not_shipped',
  date_shipped date,
  expected_date_back date,
  date_received date,
  netsuite_po_number text,
  vendor text,
  item_shipped text,
  work_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valve_outsourced_items_status_chk
    check (status in ('not_shipped', 'shipped', 'received'))
);

create index if not exists idx_valve_outsourced_items_valve
  on public.valve_outsourced_items (valve_row_id);

create index if not exists idx_valve_outsourced_items_shipped
  on public.valve_outsourced_items (date_shipped desc nulls last);

-- Safe if an earlier draft of this migration already created the table without status.
alter table public.valve_outsourced_items
  add column if not exists status text;
alter table public.valve_outsourced_items
  add column if not exists date_received date;

update public.valve_outsourced_items
set status = 'not_shipped'
where status is null or btrim(status) = '';

alter table public.valve_outsourced_items
  alter column status set default 'not_shipped';

alter table public.valve_outsourced_items
  alter column status set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'valve_outsourced_items_status_chk'
      and conrelid = 'public.valve_outsourced_items'::regclass
  ) then
    alter table public.valve_outsourced_items
      add constraint valve_outsourced_items_status_chk
      check (status in ('not_shipped', 'shipped', 'received'));
  end if;
end $$;

drop trigger if exists valve_outsourced_items_set_updated_at on public.valve_outsourced_items;
create trigger valve_outsourced_items_set_updated_at
before update on public.valve_outsourced_items
for each row
execute function public.set_updated_at();

alter table public.valve_outsourced_items enable row level security;

drop policy if exists "public read valve outsourced items" on public.valve_outsourced_items;
create policy "public read valve outsourced items"
on public.valve_outsourced_items
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve outsourced items" on public.valve_outsourced_items;
create policy "public insert valve outsourced items"
on public.valve_outsourced_items
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update valve outsourced items" on public.valve_outsourced_items;
create policy "public update valve outsourced items"
on public.valve_outsourced_items
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete valve outsourced items" on public.valve_outsourced_items;
create policy "public delete valve outsourced items"
on public.valve_outsourced_items
for delete
to anon, authenticated
using (true);

-- Add Vendor options in Manage lists → Job field lists → Vendor.
-- (No seed rows; start empty like Manufacturer.)

commit;
