-- Run in Supabase SQL Editor.
-- Stores ASME B16.10 face-to-face reference dimensions for ITP validation.

create table if not exists public.b1610_face_to_face_refs (
  id bigint generated by default as identity primary key,
  valve_type text not null check (valve_type in ('Gate', 'Globe', 'Check', 'Plug')),
  nps text not null,
  pressure_class text not null,
  end_connection text not null default 'ANY' check (end_connection in ('ANY', 'RF', 'RTJ')),
  standard_dimension numeric(10,4) not null check (standard_dimension > 0),
  tolerance numeric(10,4) not null default 0.0625 check (tolerance > 0),
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint b1610_face_to_face_refs_unique unique (valve_type, nps, pressure_class, end_connection)
);

create index if not exists idx_b1610_face_to_face_lookup
  on public.b1610_face_to_face_refs (valve_type, nps, pressure_class, end_connection);

drop trigger if exists b1610_face_to_face_refs_set_updated_at on public.b1610_face_to_face_refs;
create trigger b1610_face_to_face_refs_set_updated_at
before update on public.b1610_face_to_face_refs
for each row
execute function public.set_updated_at();

alter table public.b1610_face_to_face_refs enable row level security;

drop policy if exists "public read b1610 refs" on public.b1610_face_to_face_refs;
create policy "public read b1610 refs"
on public.b1610_face_to_face_refs
for select
to anon, authenticated
using (true);

drop policy if exists "public write b1610 refs" on public.b1610_face_to_face_refs;
create policy "public write b1610 refs"
on public.b1610_face_to_face_refs
for all
to anon, authenticated
using (true)
with check (true);
