begin;

-- Audit trail table for valve changes (who changed what and when).
create table if not exists public.valve_change_log (
  id bigint generated by default as identity primary key,
  valve_id bigint references public.valves(id) on delete set null,
  valve_row_id text,
  action text not null check (action in ('insert', 'update', 'delete')),
  changed_at timestamptz not null default now(),
  changed_by uuid,
  changed_by_email text,
  old_row jsonb,
  new_row jsonb
);

create index if not exists idx_valve_change_log_valve_id on public.valve_change_log (valve_id);
create index if not exists idx_valve_change_log_changed_at on public.valve_change_log (changed_at desc);
create index if not exists idx_valve_change_log_changed_by on public.valve_change_log (changed_by);

alter table public.valve_change_log enable row level security;

drop policy if exists "admin read valve change log" on public.valve_change_log;
create policy "admin read valve change log"
on public.valve_change_log
for select
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);

drop policy if exists "system insert valve change log" on public.valve_change_log;
create policy "system insert valve change log"
on public.valve_change_log
for insert
to authenticated
with check (true);

create or replace function public.log_valve_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  actor_email text;
begin
  actor_email :=
    coalesce(
      auth.jwt() ->> 'email',
      auth.jwt() -> 'user_metadata' ->> 'email',
      auth.jwt() -> 'app_metadata' ->> 'email'
    );

  if tg_op = 'INSERT' then
    insert into public.valve_change_log (valve_id, valve_row_id, action, changed_by, changed_by_email, old_row, new_row)
    values (new.id, new.valve_id, 'insert', auth.uid(), actor_email, null, to_jsonb(new));
    return new;
  elsif tg_op = 'UPDATE' then
    insert into public.valve_change_log (valve_id, valve_row_id, action, changed_by, changed_by_email, old_row, new_row)
    values (new.id, new.valve_id, 'update', auth.uid(), actor_email, to_jsonb(old), to_jsonb(new));
    return new;
  elsif tg_op = 'DELETE' then
    insert into public.valve_change_log (valve_id, valve_row_id, action, changed_by, changed_by_email, old_row, new_row)
    values (old.id, old.valve_id, 'delete', auth.uid(), actor_email, to_jsonb(old), null);
    return old;
  end if;

  return null;
end;
$$;

drop trigger if exists valves_audit_changes on public.valves;
create trigger valves_audit_changes
after insert or update or delete on public.valves
for each row
execute function public.log_valve_change();

-- Update permissions:
-- - all authenticated users can update valves
-- - only admins can delete valves
drop policy if exists "anon_update_valves" on public.valves;
drop policy if exists "admin_manager_update_valves" on public.valves;
drop policy if exists "supervisor_can_assign_team_jobs" on public.valves;
drop policy if exists "technician_update_own_jobs" on public.valves;
drop policy if exists "all_authenticated_update_valves" on public.valves;
drop policy if exists "anon_delete_valves" on public.valves;
drop policy if exists "admin_delete_valves" on public.valves;

create policy "all_authenticated_update_valves"
on public.valves
for update
to authenticated
using (true)
with check (true);

create policy "admin_delete_valves"
on public.valves
for delete
to authenticated
using (
  coalesce(auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') = 'admin'
);

commit;
