-- Training course packages: reusable class material holders in the Library.
-- Run in Supabase SQL Editor. Safe to re-run.

begin;

create table if not exists public.employee_training_courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_employee_training_courses_title
  on public.employee_training_courses (title);

drop trigger if exists employee_training_courses_set_updated_at on public.employee_training_courses;
create trigger employee_training_courses_set_updated_at
before update on public.employee_training_courses
for each row execute function public.set_updated_at();

alter table public.employee_training_courses enable row level security;

drop policy if exists "public read training courses" on public.employee_training_courses;
create policy "public read training courses"
on public.employee_training_courses for select to anon, authenticated using (true);

drop policy if exists "public insert training courses" on public.employee_training_courses;
create policy "public insert training courses"
on public.employee_training_courses for insert to anon, authenticated with check (true);

drop policy if exists "public update training courses" on public.employee_training_courses;
create policy "public update training courses"
on public.employee_training_courses for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete training courses" on public.employee_training_courses;
create policy "public delete training courses"
on public.employee_training_courses for delete to anon, authenticated using (true);

alter table public.employee_training_files
  add column if not exists course_id bigint references public.employee_training_courses (id) on delete cascade;

create index if not exists idx_employee_training_files_course
  on public.employee_training_files (course_id, kind, created_at desc);

alter table public.employee_training_files
  drop constraint if exists employee_training_files_kind_check;

alter table public.employee_training_files
  add constraint employee_training_files_kind_check
  check (kind in ('material', 'agenda', 'test', 'completed_test', 'signoff', 'certificate', 'other'));

comment on table public.employee_training_courses is
  'Reusable training class packages shown in Employee Training → Library.';
comment on column public.employee_training_files.course_id is
  'When set with training_id null, file belongs to a library course package.';

commit;
