-- Employee Training module: schedule, log, attendees, files, skills, TR autonumber.
-- Run once in Supabase SQL Editor.
-- Also requires migration-resource-documents-employee-training.sql if not already applied.

begin;

-- ── Autonumber sequence (TR-000001 …) ─────────────────────────────────────
create table if not exists public.employee_training_number_seq (
  id int primary key default 1 check (id = 1),
  next_num int not null default 1
);

insert into public.employee_training_number_seq (id, next_num)
values (1, 8)
on conflict (id) do nothing;
-- Default next_num=8 so first new record is TR-000008 (after spreadsheet TR-000007).

-- SECURITY DEFINER so TR allocation is not blocked by RLS on the sequence table.
create or replace function public.allocate_training_record_no()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  n int;
begin
  update public.employee_training_number_seq
  set next_num = next_num + 1
  where id = 1
  returning next_num - 1 into n;

  if n is null then
    insert into public.employee_training_number_seq (id, next_num) values (1, 2)
    on conflict (id) do update set next_num = public.employee_training_number_seq.next_num + 1
    returning next_num - 1 into n;
  end if;

  return 'TR-' || lpad(n::text, 6, '0');
end;
$$;

revoke all on function public.allocate_training_record_no() from public;
grant execute on function public.allocate_training_record_no() to authenticated, anon;

-- Sequence is an internal counter; clients only call the RPC above.
alter table public.employee_training_number_seq disable row level security;

-- ── Trainings (schedule + log) ────────────────────────────────────────────
create table if not exists public.employee_trainings (
  id bigint generated by default as identity primary key,
  record_no text not null unique,
  title text not null,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'in_progress', 'completed', 'cancelled')),
  reason text not null default ''
    check (
      reason in (
        '',
        'Annual',
        'Corrective Action',
        'Preventative Action',
        'Cross training',
        'Other'
      )
    ),
  departments text not null default '',
  car_number text not null default '',
  trainer_name text not null default '',
  scheduled_date date,
  completed_date date,
  notes text not null default '',
  recert_interval text not null default ''
    check (
      recert_interval in (
        '',
        '6_months',
        '1_year',
        '2_year',
        '3_year',
        '4_year',
        '5_year',
        '6_year',
        '7_year',
        '8_year',
        '9_year',
        '10_year'
      )
    ),
  recert_due_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_employee_trainings_status_dates
  on public.employee_trainings (status, scheduled_date desc nulls last, completed_date desc nulls last, id desc);

create index if not exists idx_employee_trainings_record_no
  on public.employee_trainings (record_no);

drop trigger if exists employee_trainings_set_updated_at on public.employee_trainings;
create trigger employee_trainings_set_updated_at
before update on public.employee_trainings
for each row execute function public.set_updated_at();

alter table public.employee_trainings enable row level security;

drop policy if exists "public read employee trainings" on public.employee_trainings;
create policy "public read employee trainings"
on public.employee_trainings for select to anon, authenticated using (true);

drop policy if exists "public insert employee trainings" on public.employee_trainings;
create policy "public insert employee trainings"
on public.employee_trainings for insert to anon, authenticated with check (true);

drop policy if exists "public update employee trainings" on public.employee_trainings;
create policy "public update employee trainings"
on public.employee_trainings for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete employee trainings" on public.employee_trainings;
create policy "public delete employee trainings"
on public.employee_trainings for delete to anon, authenticated using (true);

-- ── Attendees ─────────────────────────────────────────────────────────────
create table if not exists public.employee_training_attendees (
  id bigint generated by default as identity primary key,
  training_id bigint not null references public.employee_trainings (id) on delete cascade,
  employee_id uuid references public.employees (id) on delete set null,
  employee_name text not null default '',
  signed_off boolean not null default false,
  signed_off_at date,
  notes text not null default '',
  created_at timestamptz not null default now(),
  unique (training_id, employee_id)
);

create index if not exists idx_employee_training_attendees_training
  on public.employee_training_attendees (training_id, id);

create index if not exists idx_employee_training_attendees_employee
  on public.employee_training_attendees (employee_id);

alter table public.employee_training_attendees enable row level security;

drop policy if exists "public read training attendees" on public.employee_training_attendees;
create policy "public read training attendees"
on public.employee_training_attendees for select to anon, authenticated using (true);

drop policy if exists "public insert training attendees" on public.employee_training_attendees;
create policy "public insert training attendees"
on public.employee_training_attendees for insert to anon, authenticated with check (true);

drop policy if exists "public update training attendees" on public.employee_training_attendees;
create policy "public update training attendees"
on public.employee_training_attendees for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete training attendees" on public.employee_training_attendees;
create policy "public delete training attendees"
on public.employee_training_attendees for delete to anon, authenticated using (true);

-- ── Files (materials, tests, completed tests, sign-off) ───────────────────
create table if not exists public.employee_training_files (
  id bigint generated by default as identity primary key,
  training_id bigint references public.employee_trainings (id) on delete cascade,
  employee_id uuid references public.employees (id) on delete set null,
  kind text not null
    check (kind in ('material', 'test', 'completed_test', 'signoff', 'certificate', 'other')),
  title text not null default '',
  notes text not null default '',
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  created_at timestamptz not null default now()
);

create index if not exists idx_employee_training_files_training
  on public.employee_training_files (training_id, kind, created_at desc);

create index if not exists idx_employee_training_files_employee
  on public.employee_training_files (employee_id, kind, created_at desc);

alter table public.employee_training_files enable row level security;

drop policy if exists "public read training files" on public.employee_training_files;
create policy "public read training files"
on public.employee_training_files for select to anon, authenticated using (true);

drop policy if exists "public insert training files" on public.employee_training_files;
create policy "public insert training files"
on public.employee_training_files for insert to anon, authenticated with check (true);

drop policy if exists "public update training files" on public.employee_training_files;
create policy "public update training files"
on public.employee_training_files for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete training files" on public.employee_training_files;
create policy "public delete training files"
on public.employee_training_files for delete to anon, authenticated using (true);

-- ── Employee skill matrix (GTC / shop qualifications) ─────────────────────
create table if not exists public.employee_training_skills (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.employees (id) on delete cascade,
  skill_key text not null,
  level text not null default ''
    check (level in ('', 'in_training', 'trained', 'C', 'A', 'M', 'NEW', 'Pending')),
  shop_location text not null default '',
  notes text not null default '',
  updated_at timestamptz not null default now(),
  unique (employee_id, skill_key)
);

create index if not exists idx_employee_training_skills_employee
  on public.employee_training_skills (employee_id);

alter table public.employee_training_skills enable row level security;

drop policy if exists "public read training skills" on public.employee_training_skills;
create policy "public read training skills"
on public.employee_training_skills for select to anon, authenticated using (true);

drop policy if exists "public insert training skills" on public.employee_training_skills;
create policy "public insert training skills"
on public.employee_training_skills for insert to anon, authenticated with check (true);

drop policy if exists "public update training skills" on public.employee_training_skills;
create policy "public update training skills"
on public.employee_training_skills for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete training skills" on public.employee_training_skills;
create policy "public delete training skills"
on public.employee_training_skills for delete to anon, authenticated using (true);

commit;
