-- Customer inventory add/remove/restore activity log.
-- Safe to re-run.

create table if not exists public.inventory_events (
  id bigint generated by default as identity primary key,
  inventory_id uuid not null references public.inventory (id) on delete cascade,
  event_type text not null
    check (event_type in ('added', 'removed', 'restored')),
  reason text not null,
  po_number text,
  js_inventory_id text,
  customer text,
  customer_id_no text,
  created_by_user_id uuid,
  created_by_name text,
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_events_created_at
  on public.inventory_events (created_at desc);

create index if not exists idx_inventory_events_inventory_id
  on public.inventory_events (inventory_id);

create index if not exists idx_inventory_events_event_type
  on public.inventory_events (event_type);

alter table public.inventory_events enable row level security;

drop policy if exists "inventory_events_authenticated_select" on public.inventory_events;
create policy "inventory_events_authenticated_select"
  on public.inventory_events
  for select
  to authenticated
  using (true);

drop policy if exists "inventory_events_authenticated_insert" on public.inventory_events;
create policy "inventory_events_authenticated_insert"
  on public.inventory_events
  for insert
  to authenticated
  with check (true);

grant select, insert on public.inventory_events to authenticated;

comment on table public.inventory_events is 'Audit log of inventory adds, removals, and restores';
