-- Run in Supabase SQL Editor.
-- Stores ASME B16.34 minimum wall thickness references for ITP wall-thickness checks.

create table if not exists public.b1634_wall_thickness_refs (
  id bigint generated by default as identity primary key,
  valve_type text not null check (valve_type in ('Gate', 'Globe', 'Check', 'Plug')),
  nps text not null,
  pressure_class text not null,
  min_wall_thickness numeric(10,4) not null check (min_wall_thickness > 0),
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint b1634_wall_thickness_refs_unique unique (valve_type, nps, pressure_class)
);

create index if not exists idx_b1634_wall_thickness_lookup
  on public.b1634_wall_thickness_refs (valve_type, nps, pressure_class);

drop trigger if exists b1634_wall_thickness_refs_set_updated_at on public.b1634_wall_thickness_refs;
create trigger b1634_wall_thickness_refs_set_updated_at
before update on public.b1634_wall_thickness_refs
for each row
execute function public.set_updated_at();

alter table public.b1634_wall_thickness_refs enable row level security;

drop policy if exists "public read b1634 refs" on public.b1634_wall_thickness_refs;
create policy "public read b1634 refs"
on public.b1634_wall_thickness_refs
for select
to anon, authenticated
using (true);

drop policy if exists "public write b1634 refs" on public.b1634_wall_thickness_refs;
create policy "public write b1634 refs"
on public.b1634_wall_thickness_refs
for all
to anon, authenticated
using (true)
with check (true);
