-- Run in Supabase SQL Editor.
-- Stores ASME B16.5 flange thickness minimums for ITP reference checks.

create table if not exists public.flange_thickness_refs (
  id bigint generated by default as identity primary key,
  nps text not null,
  pressure_class text not null,
  min_thickness numeric(10,4) not null check (min_thickness > 0),
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint flange_thickness_refs_unique unique (nps, pressure_class)
);

create index if not exists idx_flange_thickness_refs_lookup
  on public.flange_thickness_refs (nps, pressure_class);

drop trigger if exists flange_thickness_refs_set_updated_at on public.flange_thickness_refs;
create trigger flange_thickness_refs_set_updated_at
before update on public.flange_thickness_refs
for each row
execute function public.set_updated_at();

alter table public.flange_thickness_refs enable row level security;

drop policy if exists "public read flange thickness refs" on public.flange_thickness_refs;
create policy "public read flange thickness refs"
on public.flange_thickness_refs
for select
to anon, authenticated
using (true);

drop policy if exists "public write flange thickness refs" on public.flange_thickness_refs;
create policy "public write flange thickness refs"
on public.flange_thickness_refs
for all
to anon, authenticated
using (true)
with check (true);
