-- Daily priority order by shop status OR finish cell (department handouts).
-- Run in Supabase SQL Editor.

create table if not exists public.status_priority_queue (
  id bigint generated by default as identity primary key,
  scope_kind text not null,
  scope_key text not null,
  valve_id text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Migrate older shop_status-only shape if it already exists.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'status_priority_queue'
      and column_name = 'shop_status'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'status_priority_queue'
      and column_name = 'scope_kind'
  ) then
    alter table public.status_priority_queue add column if not exists scope_kind text;
    alter table public.status_priority_queue add column if not exists scope_key text;
    update public.status_priority_queue
    set scope_kind = 'status',
        scope_key = shop_status
    where scope_key is null;
    alter table public.status_priority_queue alter column scope_kind set not null;
    alter table public.status_priority_queue alter column scope_key set not null;
    alter table public.status_priority_queue drop constraint if exists status_priority_queue_shop_status_valve_id_key;
    alter table public.status_priority_queue drop column if exists shop_status;
  end if;
end $$;

-- Ensure scope_kind / scope_key exist (fresh table already has them).
alter table public.status_priority_queue add column if not exists scope_kind text;
alter table public.status_priority_queue add column if not exists scope_key text;

update public.status_priority_queue
set scope_kind = coalesce(nullif(scope_kind, ''), 'status')
where scope_kind is null or scope_kind = '';

update public.status_priority_queue
set scope_key = coalesce(nullif(scope_key, ''), 'Teardown')
where scope_key is null or scope_key = '';

alter table public.status_priority_queue alter column scope_kind set not null;
alter table public.status_priority_queue alter column scope_key set not null;

alter table public.status_priority_queue drop constraint if exists status_priority_queue_scope_kind_check;
alter table public.status_priority_queue
  add constraint status_priority_queue_scope_kind_check
  check (scope_kind in ('status', 'cell'));

alter table public.status_priority_queue drop constraint if exists status_priority_queue_scope_kind_scope_key_valve_id_key;
alter table public.status_priority_queue drop constraint if exists status_priority_queue_scope_unique;
alter table public.status_priority_queue
  add constraint status_priority_queue_scope_unique
  unique (scope_kind, scope_key, valve_id);

create index if not exists idx_status_priority_queue_scope_order
  on public.status_priority_queue (scope_kind, scope_key, sort_order);

alter table public.status_priority_queue enable row level security;

drop policy if exists "public read status priority queue" on public.status_priority_queue;
create policy "public read status priority queue"
on public.status_priority_queue
for select
to anon, authenticated
using (true);

drop policy if exists "public write status priority queue" on public.status_priority_queue;
create policy "public write status priority queue"
on public.status_priority_queue
for all
to anon, authenticated
using (true)
with check (true);
