-- ITP library templates: per job type + valve type Build Scope defaults
-- (included items, hold points, measurements, notes, custom items).
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.itp_library_templates (
  id bigint generated by default as identity primary key,
  job_type text not null,
  valve_type text not null,
  scope jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint itp_library_templates_job_valve_unique unique (job_type, valve_type)
);

create index if not exists idx_itp_library_templates_job_valve
  on public.itp_library_templates (job_type, valve_type);

drop trigger if exists itp_library_templates_set_updated_at on public.itp_library_templates;
create trigger itp_library_templates_set_updated_at
before update on public.itp_library_templates
for each row
execute function public.set_updated_at();

alter table public.itp_library_templates enable row level security;

drop policy if exists "public read itp library templates" on public.itp_library_templates;
create policy "public read itp library templates"
on public.itp_library_templates
for select
to anon, authenticated
using (true);

drop policy if exists "public insert itp library templates" on public.itp_library_templates;
create policy "public insert itp library templates"
on public.itp_library_templates
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update itp library templates" on public.itp_library_templates;
create policy "public update itp library templates"
on public.itp_library_templates
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete itp library templates" on public.itp_library_templates;
create policy "public delete itp library templates"
on public.itp_library_templates
for delete
to anon, authenticated
using (true);

commit;
