-- Audit log for due date changes (reason required at time of change in the app).
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.due_date_changes (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  valve_id text not null,
  previous_due_date date,
  new_due_date date,
  reason text not null,
  changed_by_name text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_due_date_changes_changed_at on public.due_date_changes (changed_at desc);
create index if not exists idx_due_date_changes_valve_id on public.due_date_changes (valve_id);
create index if not exists idx_due_date_changes_valve_row_id on public.due_date_changes (valve_row_id);

alter table public.due_date_changes enable row level security;

drop policy if exists "public read due date changes" on public.due_date_changes;
create policy "public read due date changes"
on public.due_date_changes
for select
to anon, authenticated
using (true);

drop policy if exists "public insert due date changes" on public.due_date_changes;
create policy "public insert due date changes"
on public.due_date_changes
for insert
to anon, authenticated
with check (true);

commit;
