-- Log training hours per attendee for ongoing / recurring classes.
-- Run in Supabase SQL Editor. Safe to re-run.

begin;

create table if not exists public.employee_training_hour_entries (
  id bigint generated by default as identity primary key,
  attendee_id bigint not null references public.employee_training_attendees (id) on delete cascade,
  training_id bigint not null references public.employee_trainings (id) on delete cascade,
  employee_id uuid references public.employees (id) on delete set null,
  session_date date not null default (current_date),
  hours numeric(6, 2) not null check (hours > 0 and hours <= 9999),
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_employee_training_hour_entries_training
  on public.employee_training_hour_entries (training_id, session_date desc, id desc);

create index if not exists idx_employee_training_hour_entries_attendee
  on public.employee_training_hour_entries (attendee_id, session_date desc, id desc);

create index if not exists idx_employee_training_hour_entries_employee
  on public.employee_training_hour_entries (employee_id, session_date desc, id desc);

alter table public.employee_training_hour_entries enable row level security;

drop policy if exists "public read training hour entries" on public.employee_training_hour_entries;
create policy "public read training hour entries"
on public.employee_training_hour_entries for select to anon, authenticated using (true);

drop policy if exists "public insert training hour entries" on public.employee_training_hour_entries;
create policy "public insert training hour entries"
on public.employee_training_hour_entries for insert to anon, authenticated with check (true);

drop policy if exists "public update training hour entries" on public.employee_training_hour_entries;
create policy "public update training hour entries"
on public.employee_training_hour_entries for update to anon, authenticated using (true) with check (true);

drop policy if exists "public delete training hour entries" on public.employee_training_hour_entries;
create policy "public delete training hour entries"
on public.employee_training_hour_entries for delete to anon, authenticated using (true);

comment on table public.employee_training_hour_entries is
  'Individual hour logs for an attendee on a training record (supports ongoing classes).';

commit;
