-- Shop daily notes / to-do list (Dashboard sidebar).
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.daily_notes (
  id bigint generated by default as identity primary key,
  note_date date not null default current_date,
  body text not null,
  is_done boolean not null default false,
  completed_at timestamptz,
  assigned_to text,
  sort_order integer not null default 0,
  source text not null default 'app',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_daily_notes_open on public.daily_notes (is_done, note_date desc);
create index if not exists idx_daily_notes_note_date on public.daily_notes (note_date desc);

alter table public.daily_notes enable row level security;

drop policy if exists "public read daily notes" on public.daily_notes;
create policy "public read daily notes"
on public.daily_notes
for select
to anon, authenticated
using (true);

drop policy if exists "public write daily notes" on public.daily_notes;
create policy "public write daily notes"
on public.daily_notes
for all
to anon, authenticated
using (true)
with check (true);

commit;
