-- Quality INCRs (Internal Non-Conformance Reports) + rework disposition (NA / INCR).
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.quality_incrs (
  id bigint generated by default as identity primary key,
  incr_number text not null unique,
  status text not null default 'open'
    check (status in ('open', 'closed', 'void')),
  rework_log_id bigint references public.status_rework_log (id) on delete set null,
  valve_row_id bigint references public.valves (id) on delete set null,
  valve_id text,
  customer_name text,
  date_rejected date,
  wo_so text,
  sequence_no text,
  po_number text,
  customer_code text,
  serial_no text,
  ovation_ncmr_no text,
  part_number text,
  part_description text,
  employee_name text,
  dept_responsible text,
  location text,
  quantity text,
  work_cell text,
  item text,
  reason_code text,
  discrepancy_code text,
  nonconformance_details text,
  discrepancy_description text,
  disposition text
    check (
      disposition is null
      or disposition in (
        'accept_as_is_review',
        'scrap',
        'rework_new_wo',
        'rework_same_wo'
      )
    ),
  final_disposition text,
  labor_cost text,
  material_cost text,
  code_violation_article text,
  root_cause_corrective_action text,
  five_whys jsonb not null default '["","","","",""]'::jsonb,
  qc_approval_name text,
  qc_approval_date date,
  initiator_name text,
  initiator_date date,
  final_approval_name text,
  final_approval_date date,
  customer_signature_required boolean not null default false,
  customer_signature_date date,
  requires_corporate_ncr boolean not null default false,
  notes text,
  created_by_user_id uuid,
  created_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_quality_incrs_created_at
  on public.quality_incrs (created_at desc);

create index if not exists idx_quality_incrs_rework_log_id
  on public.quality_incrs (rework_log_id);

create index if not exists idx_quality_incrs_valve_row_id
  on public.quality_incrs (valve_row_id);

create index if not exists idx_quality_incrs_status
  on public.quality_incrs (status);

alter table public.quality_incrs enable row level security;

drop policy if exists "authenticated read quality incrs" on public.quality_incrs;
create policy "authenticated read quality incrs"
on public.quality_incrs
for select
to authenticated
using (true);

drop policy if exists "authenticated insert quality incrs" on public.quality_incrs;
create policy "authenticated insert quality incrs"
on public.quality_incrs
for insert
to authenticated
with check (true);

drop policy if exists "authenticated update quality incrs" on public.quality_incrs;
create policy "authenticated update quality incrs"
on public.quality_incrs
for update
to authenticated
using (true)
with check (true);

-- Rework row QA disposition (NA acknowledges; INCR links a created report).
alter table public.status_rework_log
  add column if not exists qa_disposition text;

alter table public.status_rework_log
  add column if not exists incr_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'status_rework_log_qa_disposition_check'
  ) then
    alter table public.status_rework_log
      add constraint status_rework_log_qa_disposition_check
      check (qa_disposition is null or qa_disposition in ('na', 'incr'));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'status_rework_log_incr_id_fkey'
  ) then
    alter table public.status_rework_log
      add constraint status_rework_log_incr_id_fkey
      foreign key (incr_id) references public.quality_incrs (id) on delete set null;
  end if;
end $$;

create index if not exists idx_status_rework_log_incr_id
  on public.status_rework_log (incr_id);

commit;
