-- Tool / MTE calibration log (micrometers, calipers, etc. from Tool Calibration Log workbook).
-- Run in Supabase SQL Editor.

begin;

create table if not exists public.tool_calibrations (
  id bigint generated by default as identity primary key,
  js_id text,
  manufacturer text,
  model text,
  tool_type text,
  serial_number text,
  calibration_date date,
  expiration_date date,
  department text,
  status text not null default 'active'
    check (status in ('active', 'out_of_service')),
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists tool_calibrations_js_id_unique
  on public.tool_calibrations (js_id)
  where js_id is not null and btrim(js_id) <> '';

create index if not exists idx_tool_calibrations_status on public.tool_calibrations (status);
create index if not exists idx_tool_calibrations_expiration on public.tool_calibrations (expiration_date);
create index if not exists idx_tool_calibrations_department on public.tool_calibrations (department);

drop trigger if exists tool_calibrations_set_updated_at on public.tool_calibrations;
create trigger tool_calibrations_set_updated_at
before update on public.tool_calibrations
for each row
execute function public.set_updated_at();

alter table public.tool_calibrations enable row level security;

drop policy if exists "public read tool calibrations" on public.tool_calibrations;
create policy "public read tool calibrations"
on public.tool_calibrations for select using (true);

drop policy if exists "authenticated insert tool calibrations" on public.tool_calibrations;
create policy "authenticated insert tool calibrations"
on public.tool_calibrations for insert to authenticated with check (true);

drop policy if exists "authenticated update tool calibrations" on public.tool_calibrations;
create policy "authenticated update tool calibrations"
on public.tool_calibrations for update to authenticated using (true) with check (true);

drop policy if exists "authenticated delete tool calibrations" on public.tool_calibrations;
create policy "authenticated delete tool calibrations"
on public.tool_calibrations for delete to authenticated using (true);

drop policy if exists "anon insert tool calibrations" on public.tool_calibrations;
create policy "anon insert tool calibrations"
on public.tool_calibrations for insert to anon with check (true);

drop policy if exists "anon update tool calibrations" on public.tool_calibrations;
create policy "anon update tool calibrations"
on public.tool_calibrations for update to anon using (true) with check (true);

drop policy if exists "anon delete tool calibrations" on public.tool_calibrations;
create policy "anon delete tool calibrations"
on public.tool_calibrations for delete to anon using (true);

commit;
