-- Rework / backward status moves on the job board.
-- Run once in Supabase SQL Editor.

begin;

create table if not exists public.status_rework_log (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  valve_id text not null,
  previous_status text not null,
  new_status text not null,
  reason text not null,
  changed_by_name text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_status_rework_log_changed_at
  on public.status_rework_log (changed_at desc);

create index if not exists idx_status_rework_log_valve_id
  on public.status_rework_log (valve_id);

create index if not exists idx_status_rework_log_valve_row_id
  on public.status_rework_log (valve_row_id);

alter table public.status_rework_log enable row level security;

drop policy if exists "public read status rework log" on public.status_rework_log;
create policy "public read status rework log"
on public.status_rework_log
for select
to anon, authenticated
using (true);

drop policy if exists "public insert status rework log" on public.status_rework_log;
create policy "public insert status rework log"
on public.status_rework_log
for insert
to anon, authenticated
with check (true);

commit;
