-- Run once in Supabase SQL Editor if you already applied an older schema.sql
-- (adds Resources → valve procedures storage).

begin;

create table if not exists public.valve_type_procedures (
  id bigint generated by default as identity primary key,
  valve_type text not null,
  title text not null,
  body text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_valve_type_procedures_vt_sort
  on public.valve_type_procedures (valve_type, sort_order, id);

drop trigger if exists valve_type_procedures_set_updated_at on public.valve_type_procedures;
create trigger valve_type_procedures_set_updated_at
before update on public.valve_type_procedures
for each row
execute function public.set_updated_at();

alter table public.valve_type_procedures enable row level security;

drop policy if exists "public read valve type procedures" on public.valve_type_procedures;
create policy "public read valve type procedures"
on public.valve_type_procedures
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve type procedures" on public.valve_type_procedures;
create policy "public insert valve type procedures"
on public.valve_type_procedures
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update valve type procedures" on public.valve_type_procedures;
create policy "public update valve type procedures"
on public.valve_type_procedures
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete valve type procedures" on public.valve_type_procedures;
create policy "public delete valve type procedures"
on public.valve_type_procedures
for delete
to anon, authenticated
using (true);

commit;
