-- Test report files (uploaded charts/scans or app-generated PDFs) linked to test_logs.
begin;

create table if not exists public.test_log_reports (
  id bigint generated by default as identity primary key,
  test_log_id bigint not null references public.test_logs(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  mime_type text,
  source text not null default 'upload' check (source in ('upload', 'generated')),
  created_at timestamptz not null default now()
);

create index if not exists idx_test_log_reports_test_log_id on public.test_log_reports(test_log_id);

alter table public.test_log_reports enable row level security;

drop policy if exists "public read test log reports" on public.test_log_reports;
create policy "public read test log reports"
on public.test_log_reports
for select
to anon, authenticated
using (true);

drop policy if exists "public write test log reports" on public.test_log_reports;
create policy "public write test log reports"
on public.test_log_reports
for all
to anon, authenticated
using (true)
with check (true);

commit;
