-- Run once in Supabase SQL Editor.
-- Adds Resources document storage metadata table used by Resources page uploads.

begin;

create table if not exists public.resource_documents (
  id bigint generated by default as identity primary key,
  scope text not null check (scope in ('general', 'valve_type')),
  valve_type text,
  category text not null check (category in ('general', 'weld_procedure', 'quality_control', 'iom', 'maintenance_manual', 'other')),
  title text not null,
  notes text not null default '',
  storage_path text not null unique,
  file_name text not null,
  mime_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint resource_documents_scope_valve_type_chk check (
    (scope = 'general' and valve_type is null)
    or (scope = 'valve_type' and valve_type is not null and length(trim(valve_type)) > 0)
  )
);

create index if not exists idx_resource_documents_scope_type_cat
  on public.resource_documents (scope, valve_type, category, updated_at desc, id desc);

drop trigger if exists resource_documents_set_updated_at on public.resource_documents;
create trigger resource_documents_set_updated_at
before update on public.resource_documents
for each row
execute function public.set_updated_at();

alter table public.resource_documents enable row level security;

drop policy if exists "public read resource documents" on public.resource_documents;
create policy "public read resource documents"
on public.resource_documents
for select
to anon, authenticated
using (true);

drop policy if exists "public insert resource documents" on public.resource_documents;
create policy "public insert resource documents"
on public.resource_documents
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update resource documents" on public.resource_documents;
create policy "public update resource documents"
on public.resource_documents
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete resource documents" on public.resource_documents;
create policy "public delete resource documents"
on public.resource_documents
for delete
to anon, authenticated
using (true);

commit;
