-- Incremental migration: shop sub-status on valves, technician roster, job assignments.
-- Safe to run once in Supabase SQL Editor on an existing database that already has the base schema.

begin;

alter table public.valves add column if not exists sub_status text;
alter table public.valves add column if not exists assigned_technician_ids jsonb not null default '[]'::jsonb;
alter table public.valves add column if not exists job_type text;
alter table public.valves add column if not exists material_spec text;
alter table public.valves add column if not exists drawing_po_number text;

create table if not exists public.technicians (
  id bigint generated by default as identity primary key,
  name text not null,
  employee_id text,
  work_cell_specialties text[] not null default '{}'::text[],
  group_team text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.technicians add column if not exists group_team text;
alter table public.technicians add column if not exists active boolean not null default true;
alter table public.technicians add column if not exists work_cell_specialties text[] not null default '{}'::text[];

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'technicians'
      and column_name = 'team'
  ) then
    update public.technicians
    set group_team = coalesce(group_team, team);
  end if;
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'technicians'
      and column_name = 'is_active'
  ) then
    update public.technicians
    set active = is_active
    where active is distinct from is_active;
  end if;
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'technicians'
      and column_name = 'work_cell_specialties'
      and udt_name = 'text'
  ) then
    alter table public.technicians
      alter column work_cell_specialties type text[]
      using case
        when work_cell_specialties is null or btrim(work_cell_specialties) = '' then '{}'::text[]
        else array_remove(regexp_split_to_array(work_cell_specialties, '\s*,\s*'), '')
      end;
  end if;
end
$$;

alter table public.technicians drop column if exists team;
alter table public.technicians drop column if exists is_active;

create index if not exists idx_technicians_group_team on public.technicians(group_team);
create index if not exists idx_technicians_active on public.technicians(active);

create table if not exists public.job_technicians (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  technician_id bigint not null references public.technicians(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (valve_row_id, technician_id)
);

create index if not exists idx_job_technicians_valve on public.job_technicians(valve_row_id);
create index if not exists idx_job_technicians_technician on public.job_technicians(technician_id);

insert into public.job_technicians (valve_row_id, technician_id)
select v.id, (elem.value)::bigint
from public.valves v
cross join lateral jsonb_array_elements_text(coalesce(v.assigned_technician_ids, '[]'::jsonb)) as elem(value)
where (elem.value)::bigint > 0
on conflict (valve_row_id, technician_id) do nothing;

create table if not exists public.itp_templates (
  id bigint generated by default as identity primary key,
  job_type text not null,
  valve_type text,
  step_order int not null default 0,
  step_name text not null,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_itp_templates_job_valve_sort
  on public.itp_templates (job_type, valve_type, step_order, id);

create table if not exists public.job_itp_items (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  template_step_id bigint references public.itp_templates(id) on delete set null,
  step_name text not null,
  required boolean not null default true,
  is_checked boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_job_itp_items_valve_sort
  on public.job_itp_items (valve_row_id, sort_order, id);

drop trigger if exists technicians_set_updated_at on public.technicians;
create trigger technicians_set_updated_at
before update on public.technicians
for each row
execute function public.set_updated_at();

drop trigger if exists itp_templates_set_updated_at on public.itp_templates;
create trigger itp_templates_set_updated_at
before update on public.itp_templates
for each row
execute function public.set_updated_at();

drop trigger if exists job_itp_items_set_updated_at on public.job_itp_items;
create trigger job_itp_items_set_updated_at
before update on public.job_itp_items
for each row
execute function public.set_updated_at();

alter table public.technicians replica identity full;
alter table public.itp_templates replica identity full;
alter table public.job_itp_items replica identity full;
alter table public.job_technicians replica identity full;

alter table public.technicians enable row level security;
alter table public.itp_templates enable row level security;
alter table public.job_itp_items enable row level security;
alter table public.job_technicians enable row level security;

drop policy if exists "public read technicians" on public.technicians;
create policy "public read technicians"
on public.technicians
for select
to anon, authenticated
using (true);

drop policy if exists "public insert technicians" on public.technicians;
create policy "public insert technicians"
on public.technicians
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update technicians" on public.technicians;
create policy "public update technicians"
on public.technicians
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete technicians" on public.technicians;
create policy "public delete technicians"
on public.technicians
for delete
to anon, authenticated
using (true);

drop policy if exists "public read job technicians" on public.job_technicians;
create policy "public read job technicians"
on public.job_technicians
for select
to anon, authenticated
using (true);

drop policy if exists "public write job technicians" on public.job_technicians;
create policy "public write job technicians"
on public.job_technicians
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read itp templates" on public.itp_templates;
create policy "public read itp templates"
on public.itp_templates
for select
to anon, authenticated
using (true);

drop policy if exists "public write itp templates" on public.itp_templates;
create policy "public write itp templates"
on public.itp_templates
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read job itp items" on public.job_itp_items;
create policy "public read job itp items"
on public.job_itp_items
for select
to anon, authenticated
using (true);

drop policy if exists "public write job itp items" on public.job_itp_items;
create policy "public write job itp items"
on public.job_itp_items
for all
to anon, authenticated
using (true)
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'job_technicians'
  ) then
    alter publication supabase_realtime add table public.job_technicians;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'technicians'
  ) then
    alter publication supabase_realtime add table public.technicians;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'itp_templates'
  ) then
    alter publication supabase_realtime add table public.itp_templates;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'job_itp_items'
  ) then
    alter publication supabase_realtime add table public.job_itp_items;
  end if;
end
$$;

commit;
