-- JS Job Board App - Supabase schema
-- Run this in Supabase SQL Editor.

begin;

create extension if not exists pgcrypto;

create table if not exists public.valves (
  id bigint generated by default as identity primary key,
  valve_id text not null unique,
  customer text,
  cell text,
  size text,
  status text not null,
  test_type text,
  valve_type text,
  bowl_type text,
  order_type text,
  due_date date,
  date_tested date,
  date_closed date,
  description text,
  notes text,
  is_turnaround boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.priority_queue (
  id bigint generated by default as identity primary key,
  valve_id text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.test_logs (
  id bigint generated by default as identity primary key,
  tested_on date not null,
  valve_id text not null,
  size text,
  pressure text,
  manufacturer text,
  valve_type text,
  test_type text,
  worked text,
  pass_fail text,
  action_taken text,
  tester text,
  created_at timestamptz not null default now()
);

-- Canonical customer names for dropdowns (e.g. New job). valves.customer still stores the name as text.
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint customers_name_unique unique (name)
);

create index if not exists idx_customers_name on public.customers(name);

-- Dropdown options for New job (admin-managed; app falls back to constants if empty).
create table if not exists public.lookup_values (
  id bigint generated by default as identity primary key,
  category text not null,
  value text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  constraint lookup_values_category_value_key unique (category, value)
);

create index if not exists idx_lookup_values_cat_sort on public.lookup_values(category, sort_order, id);

-- Files / photos for jobs (paths live in Storage bucket valve-attachments).
create table if not exists public.valve_attachments (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  mime_type text,
  kind text not null default 'file',
  created_at timestamptz not null default now(),
  constraint valve_attachments_kind_chk check (kind in ('photo', 'file')),
  constraint valve_attachments_storage_path_key unique (storage_path)
);

create index if not exists idx_valve_attachments_valve on public.valve_attachments(valve_row_id);

-- Inspection & Test Plan (ITP) — one document per job card (valves.id).
create table if not exists public.valve_itp (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valve_itp_valve_unique unique (valve_row_id)
);

create index if not exists idx_valve_itp_valve on public.valve_itp(valve_row_id);

alter table public.valve_itp add column if not exists itp_data jsonb not null default '{}'::jsonb;

-- Shop procedures / work instructions by valve type (Resources page).
create table if not exists public.valve_type_procedures (
  id bigint generated by default as identity primary key,
  valve_type text not null,
  title text not null,
  body text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_valve_type_procedures_vt_sort
  on public.valve_type_procedures (valve_type, sort_order, id);

-- Add lookup columns on existing databases (no-op if already present).
alter table public.valves add column if not exists test_type text;
alter table public.valves add column if not exists valve_type text;
alter table public.valves add column if not exists order_type text;
alter table public.valves add column if not exists description text;
alter table public.valves add column if not exists bowl_type text;
alter table public.valves add column if not exists notes text;
alter table public.valves add column if not exists sub_status text;
alter table public.valves add column if not exists assigned_technician_ids jsonb not null default '[]'::jsonb;
alter table public.valves add column if not exists assigned_technician_id bigint references public.technicians(id);
alter table public.valves add column if not exists assigned_by bigint references public.technicians(id);
alter table public.valves add column if not exists assigned_at timestamptz;
alter table public.valves add column if not exists assignment_notes text;
alter table public.valves add column if not exists needs_attention boolean not null default false;
alter table public.valves add column if not exists job_type text;
alter table public.valves add column if not exists material_spec text;
alter table public.valves add column if not exists drawing_po_number text;

create table if not exists public.technicians (
  id bigint generated by default as identity primary key,
  name text not null,
  employee_id text,
  work_cell_specialties text[] not null default '{}'::text[],
  group_team text,
  active boolean not null default true,
  user_id uuid references auth.users(id),
  login_email text,
  role text not null default 'technician' check (role in ('admin', 'manager', 'supervisor', 'technician')),
  supervisor_id bigint references public.technicians(id),
  manager_id bigint references public.technicians(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_technicians_group_team on public.technicians(group_team);
create index if not exists idx_technicians_active on public.technicians(active);
create index if not exists idx_technicians_user_id on public.technicians(user_id);
create index if not exists idx_technicians_supervisor_id on public.technicians(supervisor_id);
create index if not exists idx_technicians_manager_id on public.technicians(manager_id);

create table if not exists public.job_technicians (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  technician_id bigint not null references public.technicians(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (valve_row_id, technician_id)
);

create index if not exists idx_job_technicians_valve on public.job_technicians(valve_row_id);
create index if not exists idx_job_technicians_technician on public.job_technicians(technician_id);

create table if not exists public.itp_templates (
  id bigint generated by default as identity primary key,
  job_type text not null,
  valve_type text,
  step_order int not null default 0,
  step_name text not null,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_itp_templates_job_valve_sort
  on public.itp_templates (job_type, valve_type, step_order, id);

create table if not exists public.job_itp_items (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  template_step_id bigint references public.itp_templates(id) on delete set null,
  step_name text not null,
  required boolean not null default true,
  is_checked boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_job_itp_items_valve_sort
  on public.job_itp_items (valve_row_id, sort_order, id);

create table if not exists public.job_assignment_history (
  id uuid primary key default gen_random_uuid(),
  job_id bigint not null references public.valves(id) on delete cascade,
  assigned_to bigint references public.technicians(id),
  assigned_by bigint references public.technicians(id),
  assigned_at timestamptz not null default now(),
  notes text,
  action text not null check (action in ('assigned', 'reassigned', 'unassigned'))
);

create index if not exists idx_valves_status on public.valves(status);
create index if not exists idx_valves_date_closed on public.valves(date_closed desc nulls last);
create index if not exists idx_valves_customer on public.valves(customer);
create index if not exists idx_valves_valve_id on public.valves(valve_id);
create index if not exists idx_valves_assigned_technician_id on public.valves(assigned_technician_id);
create index if not exists idx_priority_queue_valve_id on public.priority_queue(valve_id);
create index if not exists idx_test_logs_valve_id on public.test_logs(valve_id);
create index if not exists idx_test_logs_tested_on on public.test_logs(tested_on desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists valves_set_updated_at on public.valves;
create trigger valves_set_updated_at
before update on public.valves
for each row
execute function public.set_updated_at();

drop trigger if exists valve_itp_set_updated_at on public.valve_itp;
create trigger valve_itp_set_updated_at
before update on public.valve_itp
for each row
execute function public.set_updated_at();

drop trigger if exists valve_type_procedures_set_updated_at on public.valve_type_procedures;
create trigger valve_type_procedures_set_updated_at
before update on public.valve_type_procedures
for each row
execute function public.set_updated_at();

drop trigger if exists technicians_set_updated_at on public.technicians;
create trigger technicians_set_updated_at
before update on public.technicians
for each row
execute function public.set_updated_at();

drop trigger if exists itp_templates_set_updated_at on public.itp_templates;
create trigger itp_templates_set_updated_at
before update on public.itp_templates
for each row
execute function public.set_updated_at();

drop trigger if exists job_itp_items_set_updated_at on public.job_itp_items;
create trigger job_itp_items_set_updated_at
before update on public.job_itp_items
for each row
execute function public.set_updated_at();

alter table public.valves replica identity full;
alter table public.priority_queue replica identity full;
alter table public.test_logs replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'valves'
  ) then
    alter publication supabase_realtime add table public.valves;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'priority_queue'
  ) then
    alter publication supabase_realtime add table public.priority_queue;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'test_logs'
  ) then
    alter publication supabase_realtime add table public.test_logs;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'technicians'
  ) then
    alter publication supabase_realtime add table public.technicians;
  end if;
end
$$;

alter table public.technicians replica identity full;

alter table public.valves enable row level security;
alter table public.priority_queue enable row level security;
alter table public.test_logs enable row level security;
alter table public.customers enable row level security;
alter table public.lookup_values enable row level security;
alter table public.valve_attachments enable row level security;
alter table public.valve_itp enable row level security;
alter table public.valve_type_procedures enable row level security;
alter table public.technicians enable row level security;
alter table public.itp_templates enable row level security;
alter table public.job_itp_items enable row level security;
alter table public.job_technicians enable row level security;

drop policy if exists "public read valves" on public.valves;
drop policy if exists "public update valves" on public.valves;
drop policy if exists "public insert valves" on public.valves;
drop policy if exists "admin_manager_full_access" on public.valves;
drop policy if exists "anon_read_valves" on public.valves;
drop policy if exists "authenticated_read_valves" on public.valves;
drop policy if exists "anon_insert_valves" on public.valves;
drop policy if exists "anon_update_valves" on public.valves;
drop policy if exists "admin_manager_insert_valves" on public.valves;
drop policy if exists "admin_manager_update_valves" on public.valves;
drop policy if exists "supervisor_can_see_team_jobs" on public.valves;
drop policy if exists "supervisor_can_assign_team_jobs" on public.valves;
drop policy if exists "technician_own_jobs" on public.valves;
drop policy if exists "technician_update_own_jobs" on public.valves;

create policy "anon_read_valves"
on public.valves
for select
to anon
using (true);

create policy "authenticated_read_valves"
on public.valves
for select
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
  or (
    coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') = 'supervisor'
    and (
      public.valves.assigned_technician_id in (
        select t.id
        from public.technicians t
        where t.supervisor_id = (select me.id from public.technicians me where me.user_id = auth.uid())
      )
      or public.valves.assigned_technician_id = (select me.id from public.technicians me where me.user_id = auth.uid())
    )
  )
  or (
    coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('technician','tech')
    and public.valves.assigned_technician_id = (select me.id from public.technicians me where me.user_id = auth.uid())
  )
);

create policy "anon_insert_valves"
on public.valves
for insert
to anon
with check (true);

create policy "admin_manager_insert_valves"
on public.valves
for insert
to authenticated
with check (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "anon_update_valves"
on public.valves
for update
to anon
using (true)
with check (true);

create policy "admin_manager_update_valves"
on public.valves
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
)
with check (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "supervisor_can_assign_team_jobs"
on public.valves
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') = 'supervisor'
)
with check (
  public.valves.assigned_technician_id in (
    select t.id
    from public.technicians t
    where t.supervisor_id = (select me.id from public.technicians me where me.user_id = auth.uid())
  )
);

create policy "technician_update_own_jobs"
on public.valves
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('technician','tech')
  and public.valves.assigned_technician_id = (select me.id from public.technicians me where me.user_id = auth.uid())
)
with check (
  public.valves.assigned_technician_id = (select me.id from public.technicians me where me.user_id = auth.uid())
);

drop policy if exists "public read priority queue" on public.priority_queue;
create policy "public read priority queue"
on public.priority_queue
for select
to anon, authenticated
using (true);

drop policy if exists "public write priority queue" on public.priority_queue;
create policy "public write priority queue"
on public.priority_queue
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read test logs" on public.test_logs;
create policy "public read test logs"
on public.test_logs
for select
to anon, authenticated
using (true);

drop policy if exists "public write test logs" on public.test_logs;
create policy "public write test logs"
on public.test_logs
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read customers" on public.customers;
create policy "public read customers"
on public.customers
for select
to anon, authenticated
using (true);

-- Inserts are open to anon like valves; the app only shows “add customer” for Admin. True DB-level
-- admin-only requires Supabase Auth (or a server using the service role).
drop policy if exists "public insert customers" on public.customers;
create policy "public insert customers"
on public.customers
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update customers" on public.customers;
create policy "public update customers"
on public.customers
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete customers" on public.customers;
create policy "public delete customers"
on public.customers
for delete
to anon, authenticated
using (true);

drop policy if exists "public read lookup values" on public.lookup_values;
create policy "public read lookup values"
on public.lookup_values
for select
to anon, authenticated
using (true);

drop policy if exists "public insert lookup values" on public.lookup_values;
create policy "public insert lookup values"
on public.lookup_values
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update lookup values" on public.lookup_values;
create policy "public update lookup values"
on public.lookup_values
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete lookup values" on public.lookup_values;
create policy "public delete lookup values"
on public.lookup_values
for delete
to anon, authenticated
using (true);

drop policy if exists "public read valve attachments" on public.valve_attachments;
create policy "public read valve attachments"
on public.valve_attachments
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve attachments" on public.valve_attachments;
create policy "public insert valve attachments"
on public.valve_attachments
for insert
to anon, authenticated
with check (true);

drop policy if exists "public delete valve attachments" on public.valve_attachments;
create policy "public delete valve attachments"
on public.valve_attachments
for delete
to anon, authenticated
using (true);

drop policy if exists "public read valve itp" on public.valve_itp;
create policy "public read valve itp"
on public.valve_itp
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve itp" on public.valve_itp;
create policy "public insert valve itp"
on public.valve_itp
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update valve itp" on public.valve_itp;
create policy "public update valve itp"
on public.valve_itp
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete valve itp" on public.valve_itp;
create policy "public delete valve itp"
on public.valve_itp
for delete
to anon, authenticated
using (true);

drop policy if exists "public read valve type procedures" on public.valve_type_procedures;
create policy "public read valve type procedures"
on public.valve_type_procedures
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve type procedures" on public.valve_type_procedures;
create policy "public insert valve type procedures"
on public.valve_type_procedures
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update valve type procedures" on public.valve_type_procedures;
create policy "public update valve type procedures"
on public.valve_type_procedures
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete valve type procedures" on public.valve_type_procedures;
create policy "public delete valve type procedures"
on public.valve_type_procedures
for delete
to anon, authenticated
using (true);

drop policy if exists "public read technicians" on public.technicians;
drop policy if exists "public insert technicians" on public.technicians;
drop policy if exists "public update technicians" on public.technicians;
drop policy if exists "public delete technicians" on public.technicians;
drop policy if exists "admin_manager_full_technicians" on public.technicians;
drop policy if exists "anon_read_technicians" on public.technicians;
drop policy if exists "authenticated_read_technicians" on public.technicians;
drop policy if exists "anon_insert_technicians" on public.technicians;
drop policy if exists "anon_update_technicians" on public.technicians;
drop policy if exists "anon_delete_technicians" on public.technicians;
drop policy if exists "admin_manager_insert_technicians" on public.technicians;
drop policy if exists "admin_manager_update_technicians" on public.technicians;
drop policy if exists "admin_manager_delete_technicians" on public.technicians;
drop policy if exists "technician read own profile" on public.technicians;

create policy "anon_read_technicians"
on public.technicians
for select
to anon
using (true);

create policy "authenticated_read_technicians"
on public.technicians
for select
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
  or user_id = auth.uid()
);

create policy "anon_insert_technicians"
on public.technicians
for insert
to anon
with check (true);

create policy "admin_manager_insert_technicians"
on public.technicians
for insert
to authenticated
with check (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "anon_update_technicians"
on public.technicians
for update
to anon
using (true)
with check (true);

create policy "admin_manager_update_technicians"
on public.technicians
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
)
with check (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "anon_delete_technicians"
on public.technicians
for delete
to anon
using (true);

create policy "admin_manager_delete_technicians"
on public.technicians
for delete
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "technician read own profile"
on public.technicians
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "public read job technicians" on public.job_technicians;
create policy "public read job technicians"
on public.job_technicians
for select
to anon, authenticated
using (true);

drop policy if exists "public write job technicians" on public.job_technicians;
create policy "public write job technicians"
on public.job_technicians
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read itp templates" on public.itp_templates;
create policy "public read itp templates"
on public.itp_templates
for select
to anon, authenticated
using (true);

drop policy if exists "public write itp templates" on public.itp_templates;
create policy "public write itp templates"
on public.itp_templates
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read job itp items" on public.job_itp_items;
create policy "public read job itp items"
on public.job_itp_items
for select
to anon, authenticated
using (true);

drop policy if exists "public write job itp items" on public.job_itp_items;
create policy "public write job itp items"
on public.job_itp_items
for all
to anon, authenticated
using (true)
with check (true);

-- Storage bucket for uploads (public read URLs; same RLS model as tables).
insert into storage.buckets (id, name, public)
values ('valve-attachments', 'valve-attachments', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "valve_attachments storage select" on storage.objects;
create policy "valve_attachments storage select"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'valve-attachments');

drop policy if exists "valve_attachments storage insert" on storage.objects;
create policy "valve_attachments storage insert"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'valve-attachments');

drop policy if exists "valve_attachments storage delete" on storage.objects;
create policy "valve_attachments storage delete"
on storage.objects
for delete
to anon, authenticated
using (bucket_id = 'valve-attachments');

commit;

-- Attachments: if insert into storage.buckets fails, create bucket "valve-attachments" in Dashboard
-- (public) and re-run only the storage policy block from this file.
--
-- Optional: seed job dropdowns — run supabase/seed-lookup-values.sql once (after lookup_values exists).
-- Optional: seed customers from Excel list — run supabase/seed-customers-from-spreadsheet.sql once.
--
-- Optional: one-time backfill customer list from existing valve rows (run in SQL Editor after customers exists):
-- insert into public.customers (name)
-- select distinct trim(customer) from public.valves
-- where customer is not null and trim(customer) <> ''
-- on conflict (name) do nothing;

-- Optional starter rows:
-- insert into public.valves (valve_id, customer, cell, size, status, due_date) values
-- ('488518-6', 'ABC Refining', 'Finish Cell', '6"', 'Arrived - Not Started', current_date + 2),
-- ('488519-2', 'Pipeline Co', 'Cell 4', '2"', 'Teardown', current_date + 5),
-- ('488520-3', 'West Plant', 'Cell 1', '3"', 'Testing', current_date + 1);
--
-- insert into public.priority_queue (valve_id) values ('488518-6');
