-- JS Job Board App - Supabase schema
-- Run this in Supabase SQL Editor.

begin;

create extension if not exists pgcrypto;

create table if not exists public.valves (
  id bigint generated by default as identity primary key,
  valve_id text not null unique,
  customer text,
  cell text,
  size text,
  status text not null,
  test_type text,
  valve_type text,
  bowl_type text,
  order_type text,
  due_date date,
  date_tested date,
  date_closed date,
  description text,
  notes text,
  is_turnaround boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.priority_queue (
  id bigint generated by default as identity primary key,
  valve_id text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_notes (
  id bigint generated by default as identity primary key,
  note_date date not null default current_date,
  body text not null,
  is_done boolean not null default false,
  completed_at timestamptz,
  assigned_to text,
  sort_order integer not null default 0,
  source text not null default 'app',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.test_logs (
  id bigint generated by default as identity primary key,
  tested_on date not null,
  valve_id text not null,
  size text,
  pressure text,
  manufacturer text,
  valve_type text,
  test_type text,
  worked text,
  pass_fail text,
  action_taken text,
  tester text,
  created_at timestamptz not null default now()
);

-- Canonical customer names for dropdowns (e.g. New job). valves.customer still stores the name as text.
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint customers_name_unique unique (name)
);

create index if not exists idx_customers_name on public.customers(name);

-- Dropdown options for New job (admin-managed; app falls back to constants if empty).
create table if not exists public.lookup_values (
  id bigint generated by default as identity primary key,
  category text not null,
  value text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  constraint lookup_values_category_value_key unique (category, value)
);

create index if not exists idx_lookup_values_cat_sort on public.lookup_values(category, sort_order, id);

-- Files / photos for jobs (paths live in Storage bucket valve-attachments).
create table if not exists public.valve_attachments (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  storage_path text not null,
  file_name text not null,
  mime_type text,
  kind text not null default 'file',
  created_at timestamptz not null default now(),
  constraint valve_attachments_kind_chk check (kind in ('photo', 'file')),
  constraint valve_attachments_storage_path_key unique (storage_path)
);

create index if not exists idx_valve_attachments_valve on public.valve_attachments(valve_row_id);

-- Inspection & Test Plan (ITP) — one document per job card (valves.id).
create table if not exists public.valve_itp (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint valve_itp_valve_unique unique (valve_row_id)
);

create index if not exists idx_valve_itp_valve on public.valve_itp(valve_row_id);

alter table public.valve_itp add column if not exists itp_data jsonb not null default '{}'::jsonb;

-- Shop procedures / work instructions by valve type (Resources page).
create table if not exists public.valve_type_procedures (
  id bigint generated by default as identity primary key,
  valve_type text not null,
  title text not null,
  body text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_valve_type_procedures_vt_sort
  on public.valve_type_procedures (valve_type, sort_order, id);

-- Add lookup columns on existing databases (no-op if already present).
alter table public.valves add column if not exists test_type text;
alter table public.valves add column if not exists valve_type text;
alter table public.valves add column if not exists order_type text;
alter table public.valves add column if not exists description text;
alter table public.valves add column if not exists bowl_type text;
alter table public.valves add column if not exists notes text;
alter table public.valves add column if not exists sub_status text;
alter table public.valves add column if not exists assigned_technician_ids jsonb not null default '[]'::jsonb;
alter table public.valves add column if not exists assigned_technician_id bigint references public.technicians(id);
alter table public.valves add column if not exists assigned_by bigint references public.technicians(id);
alter table public.valves add column if not exists assigned_at timestamptz;
alter table public.valves add column if not exists assignment_notes text;
alter table public.valves add column if not exists needs_attention boolean not null default false;
alter table public.valves add column if not exists job_type text;
alter table public.valves add column if not exists material_spec text;
alter table public.valves add column if not exists drawing_po_number text;

create table if not exists public.technicians (
  id bigint generated by default as identity primary key,
  name text not null,
  employee_id text,
  work_cell_specialties text[] not null default '{}'::text[],
  group_team text,
  active boolean not null default true,
  user_id uuid references auth.users(id),
  login_email text,
  role text not null default 'technician' check (role in ('admin', 'manager', 'supervisor', 'technician')),
  supervisor_id bigint references public.technicians(id),
  manager_id bigint references public.technicians(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_technicians_group_team on public.technicians(group_team);
create index if not exists idx_technicians_active on public.technicians(active);
create index if not exists idx_technicians_user_id on public.technicians(user_id);
create index if not exists idx_technicians_supervisor_id on public.technicians(supervisor_id);
create index if not exists idx_technicians_manager_id on public.technicians(manager_id);

create table if not exists public.job_technicians (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  technician_id bigint not null references public.technicians(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (valve_row_id, technician_id)
);

create index if not exists idx_job_technicians_valve on public.job_technicians(valve_row_id);
create index if not exists idx_job_technicians_technician on public.job_technicians(technician_id);

create table if not exists public.itp_templates (
  id bigint generated by default as identity primary key,
  job_type text not null,
  valve_type text,
  step_order int not null default 0,
  step_name text not null,
  required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_itp_templates_job_valve_sort
  on public.itp_templates (job_type, valve_type, step_order, id);

create table if not exists public.job_itp_items (
  id bigint generated by default as identity primary key,
  valve_row_id bigint not null references public.valves(id) on delete cascade,
  template_step_id bigint references public.itp_templates(id) on delete set null,
  step_name text not null,
  required boolean not null default true,
  is_checked boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_job_itp_items_valve_sort
  on public.job_itp_items (valve_row_id, sort_order, id);

create table if not exists public.flange_thickness_refs (
  id bigint generated by default as identity primary key,
  nps text not null,
  pressure_class text not null,
  min_thickness numeric(10,4) not null check (min_thickness > 0),
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint flange_thickness_refs_unique unique (nps, pressure_class)
);

create index if not exists idx_flange_thickness_refs_lookup
  on public.flange_thickness_refs (nps, pressure_class);

create table if not exists public.b1610_face_to_face_refs (
  id bigint generated by default as identity primary key,
  valve_type text not null check (valve_type in ('Gate', 'Globe', 'Check', 'Plug')),
  nps text not null,
  pressure_class text not null,
  end_connection text not null default 'ANY' check (end_connection in ('ANY', 'RF', 'RTJ')),
  standard_dimension numeric(10,4) not null check (standard_dimension > 0),
  tolerance numeric(10,4) not null default 0.0625 check (tolerance > 0),
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint b1610_face_to_face_refs_unique unique (valve_type, nps, pressure_class, end_connection)
);

create index if not exists idx_b1610_face_to_face_lookup
  on public.b1610_face_to_face_refs (valve_type, nps, pressure_class, end_connection);

create table if not exists public.b1634_wall_thickness_refs (
  id bigint generated by default as identity primary key,
  valve_type text not null check (valve_type in ('Gate', 'Globe', 'Check', 'Plug')),
  nps text not null,
  pressure_class text not null,
  min_wall_thickness numeric(10,4) not null check (min_wall_thickness > 0),
  notes text,
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint b1634_wall_thickness_refs_unique unique (valve_type, nps, pressure_class)
);

create index if not exists idx_b1634_wall_thickness_lookup
  on public.b1634_wall_thickness_refs (valve_type, nps, pressure_class);

create table if not exists public.job_assignment_history (
  id uuid primary key default gen_random_uuid(),
  job_id bigint not null references public.valves(id) on delete cascade,
  assigned_to bigint references public.technicians(id),
  assigned_by bigint references public.technicians(id),
  assigned_at timestamptz not null default now(),
  notes text,
  action text not null check (action in ('assigned', 'reassigned', 'unassigned'))
);

create index if not exists idx_valves_status on public.valves(status);
create index if not exists idx_valves_date_closed on public.valves(date_closed desc nulls last);
create index if not exists idx_valves_customer on public.valves(customer);
create index if not exists idx_valves_valve_id on public.valves(valve_id);
create index if not exists idx_valves_assigned_technician_id on public.valves(assigned_technician_id);
create index if not exists idx_priority_queue_valve_id on public.priority_queue(valve_id);
create index if not exists idx_daily_notes_open on public.daily_notes (is_done, note_date desc);
create index if not exists idx_daily_notes_note_date on public.daily_notes (note_date desc);
create index if not exists idx_test_logs_valve_id on public.test_logs(valve_id);
create index if not exists idx_test_logs_tested_on on public.test_logs(tested_on desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists valves_set_updated_at on public.valves;
create trigger valves_set_updated_at
before update on public.valves
for each row
execute function public.set_updated_at();

drop trigger if exists valve_itp_set_updated_at on public.valve_itp;
create trigger valve_itp_set_updated_at
before update on public.valve_itp
for each row
execute function public.set_updated_at();

drop trigger if exists valve_type_procedures_set_updated_at on public.valve_type_procedures;
create trigger valve_type_procedures_set_updated_at
before update on public.valve_type_procedures
for each row
execute function public.set_updated_at();

drop trigger if exists technicians_set_updated_at on public.technicians;
create trigger technicians_set_updated_at
before update on public.technicians
for each row
execute function public.set_updated_at();

drop trigger if exists itp_templates_set_updated_at on public.itp_templates;
create trigger itp_templates_set_updated_at
before update on public.itp_templates
for each row
execute function public.set_updated_at();

drop trigger if exists job_itp_items_set_updated_at on public.job_itp_items;
create trigger job_itp_items_set_updated_at
before update on public.job_itp_items
for each row
execute function public.set_updated_at();

drop trigger if exists flange_thickness_refs_set_updated_at on public.flange_thickness_refs;
create trigger flange_thickness_refs_set_updated_at
before update on public.flange_thickness_refs
for each row
execute function public.set_updated_at();

drop trigger if exists b1610_face_to_face_refs_set_updated_at on public.b1610_face_to_face_refs;
create trigger b1610_face_to_face_refs_set_updated_at
before update on public.b1610_face_to_face_refs
for each row
execute function public.set_updated_at();

drop trigger if exists b1634_wall_thickness_refs_set_updated_at on public.b1634_wall_thickness_refs;
create trigger b1634_wall_thickness_refs_set_updated_at
before update on public.b1634_wall_thickness_refs
for each row
execute function public.set_updated_at();

alter table public.valves replica identity full;
alter table public.priority_queue replica identity full;
alter table public.test_logs replica identity full;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'valves'
  ) then
    alter publication supabase_realtime add table public.valves;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'priority_queue'
  ) then
    alter publication supabase_realtime add table public.priority_queue;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'test_logs'
  ) then
    alter publication supabase_realtime add table public.test_logs;
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'technicians'
  ) then
    alter publication supabase_realtime add table public.technicians;
  end if;
end
$$;

alter table public.technicians replica identity full;

alter table public.valves enable row level security;
alter table public.priority_queue enable row level security;
alter table public.daily_notes enable row level security;
alter table public.test_logs enable row level security;
alter table public.customers enable row level security;
alter table public.lookup_values enable row level security;
alter table public.valve_attachments enable row level security;
alter table public.valve_itp enable row level security;
alter table public.valve_type_procedures enable row level security;
alter table public.technicians enable row level security;
alter table public.itp_templates enable row level security;
alter table public.job_itp_items enable row level security;
alter table public.job_technicians enable row level security;
alter table public.flange_thickness_refs enable row level security;
alter table public.b1610_face_to_face_refs enable row level security;
alter table public.b1634_wall_thickness_refs enable row level security;

drop policy if exists "public read valves" on public.valves;
drop policy if exists "public update valves" on public.valves;
drop policy if exists "public insert valves" on public.valves;
drop policy if exists "admin_manager_full_access" on public.valves;
drop policy if exists "anon_read_valves" on public.valves;
drop policy if exists "authenticated_read_valves" on public.valves;
drop policy if exists "anon_insert_valves" on public.valves;
drop policy if exists "anon_update_valves" on public.valves;
drop policy if exists "admin_manager_insert_valves" on public.valves;
drop policy if exists "authenticated_insert_valves" on public.valves;
drop policy if exists "admin_manager_update_valves" on public.valves;
drop policy if exists "supervisor_can_see_team_jobs" on public.valves;
drop policy if exists "supervisor_can_assign_team_jobs" on public.valves;
drop policy if exists "technician_own_jobs" on public.valves;
drop policy if exists "technician_update_own_jobs" on public.valves;

create policy "anon_read_valves"
on public.valves
for select
to anon
using (true);

create policy "authenticated_read_valves"
on public.valves
for select
to authenticated
using (true);

create policy "anon_insert_valves"
on public.valves
for insert
to anon
with check (true);

create policy "authenticated_insert_valves"
on public.valves
for insert
to authenticated
with check (true);

create policy "anon_update_valves"
on public.valves
for update
to anon
using (true)
with check (true);

create policy "admin_manager_update_valves"
on public.valves
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
)
with check (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "supervisor_can_assign_team_jobs"
on public.valves
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') = 'supervisor'
)
with check (
  public.valves.assigned_technician_id in (
    select t.id
    from public.technicians t
    where t.supervisor_id = (select me.id from public.technicians me where me.user_id = auth.uid())
  )
);

create policy "technician_update_own_jobs"
on public.valves
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('technician','tech')
  and public.valves.assigned_technician_id = (select me.id from public.technicians me where me.user_id = auth.uid())
)
with check (
  public.valves.assigned_technician_id = (select me.id from public.technicians me where me.user_id = auth.uid())
);

drop policy if exists "public read priority queue" on public.priority_queue;
create policy "public read priority queue"
on public.priority_queue
for select
to anon, authenticated
using (true);

drop policy if exists "public write priority queue" on public.priority_queue;
create policy "public write priority queue"
on public.priority_queue
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read daily notes" on public.daily_notes;
create policy "public read daily notes"
on public.daily_notes
for select
to anon, authenticated
using (true);

drop policy if exists "public write daily notes" on public.daily_notes;
create policy "public write daily notes"
on public.daily_notes
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read test logs" on public.test_logs;
create policy "public read test logs"
on public.test_logs
for select
to anon, authenticated
using (true);

drop policy if exists "public write test logs" on public.test_logs;
create policy "public write test logs"
on public.test_logs
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read customers" on public.customers;
create policy "public read customers"
on public.customers
for select
to anon, authenticated
using (true);

-- Inserts are open to anon like valves; the app only shows “add customer” for Admin. True DB-level
-- admin-only requires Supabase Auth (or a server using the service role).
drop policy if exists "public insert customers" on public.customers;
create policy "public insert customers"
on public.customers
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update customers" on public.customers;
create policy "public update customers"
on public.customers
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete customers" on public.customers;
create policy "public delete customers"
on public.customers
for delete
to anon, authenticated
using (true);

drop policy if exists "public read lookup values" on public.lookup_values;
create policy "public read lookup values"
on public.lookup_values
for select
to anon, authenticated
using (true);

drop policy if exists "public insert lookup values" on public.lookup_values;
create policy "public insert lookup values"
on public.lookup_values
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update lookup values" on public.lookup_values;
create policy "public update lookup values"
on public.lookup_values
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete lookup values" on public.lookup_values;
create policy "public delete lookup values"
on public.lookup_values
for delete
to anon, authenticated
using (true);

drop policy if exists "public read valve attachments" on public.valve_attachments;
create policy "public read valve attachments"
on public.valve_attachments
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve attachments" on public.valve_attachments;
create policy "public insert valve attachments"
on public.valve_attachments
for insert
to anon, authenticated
with check (true);

drop policy if exists "public delete valve attachments" on public.valve_attachments;
create policy "public delete valve attachments"
on public.valve_attachments
for delete
to anon, authenticated
using (true);

drop policy if exists "public read valve itp" on public.valve_itp;
create policy "public read valve itp"
on public.valve_itp
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve itp" on public.valve_itp;
create policy "public insert valve itp"
on public.valve_itp
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update valve itp" on public.valve_itp;
create policy "public update valve itp"
on public.valve_itp
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete valve itp" on public.valve_itp;
create policy "public delete valve itp"
on public.valve_itp
for delete
to anon, authenticated
using (true);

drop policy if exists "public read valve type procedures" on public.valve_type_procedures;
create policy "public read valve type procedures"
on public.valve_type_procedures
for select
to anon, authenticated
using (true);

drop policy if exists "public insert valve type procedures" on public.valve_type_procedures;
create policy "public insert valve type procedures"
on public.valve_type_procedures
for insert
to anon, authenticated
with check (true);

drop policy if exists "public update valve type procedures" on public.valve_type_procedures;
create policy "public update valve type procedures"
on public.valve_type_procedures
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public delete valve type procedures" on public.valve_type_procedures;
create policy "public delete valve type procedures"
on public.valve_type_procedures
for delete
to anon, authenticated
using (true);

drop policy if exists "public read technicians" on public.technicians;
drop policy if exists "public insert technicians" on public.technicians;
drop policy if exists "public update technicians" on public.technicians;
drop policy if exists "public delete technicians" on public.technicians;
drop policy if exists "admin_manager_full_technicians" on public.technicians;
drop policy if exists "anon_read_technicians" on public.technicians;
drop policy if exists "authenticated_read_technicians" on public.technicians;
drop policy if exists "anon_insert_technicians" on public.technicians;
drop policy if exists "anon_update_technicians" on public.technicians;
drop policy if exists "anon_delete_technicians" on public.technicians;
drop policy if exists "admin_manager_insert_technicians" on public.technicians;
drop policy if exists "admin_manager_update_technicians" on public.technicians;
drop policy if exists "admin_manager_delete_technicians" on public.technicians;
drop policy if exists "technician read own profile" on public.technicians;

create policy "anon_read_technicians"
on public.technicians
for select
to anon
using (true);

create policy "authenticated_read_technicians"
on public.technicians
for select
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
  or user_id = auth.uid()
);

create policy "anon_insert_technicians"
on public.technicians
for insert
to anon
with check (true);

create policy "admin_manager_insert_technicians"
on public.technicians
for insert
to authenticated
with check (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "anon_update_technicians"
on public.technicians
for update
to anon
using (true)
with check (true);

create policy "admin_manager_update_technicians"
on public.technicians
for update
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
)
with check (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "anon_delete_technicians"
on public.technicians
for delete
to anon
using (true);

create policy "admin_manager_delete_technicians"
on public.technicians
for delete
to authenticated
using (
  coalesce(auth.jwt() ->> 'role', auth.jwt() -> 'app_metadata' ->> 'role', auth.jwt() -> 'user_metadata' ->> 'role') in ('admin','manager')
);

create policy "technician read own profile"
on public.technicians
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "public read job technicians" on public.job_technicians;
create policy "public read job technicians"
on public.job_technicians
for select
to anon, authenticated
using (true);

drop policy if exists "public write job technicians" on public.job_technicians;
create policy "public write job technicians"
on public.job_technicians
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read itp templates" on public.itp_templates;
create policy "public read itp templates"
on public.itp_templates
for select
to anon, authenticated
using (true);

drop policy if exists "public write itp templates" on public.itp_templates;
create policy "public write itp templates"
on public.itp_templates
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read job itp items" on public.job_itp_items;
create policy "public read job itp items"
on public.job_itp_items
for select
to anon, authenticated
using (true);

drop policy if exists "public write job itp items" on public.job_itp_items;
create policy "public write job itp items"
on public.job_itp_items
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read flange thickness refs" on public.flange_thickness_refs;
create policy "public read flange thickness refs"
on public.flange_thickness_refs
for select
to anon, authenticated
using (true);

drop policy if exists "public write flange thickness refs" on public.flange_thickness_refs;
create policy "public write flange thickness refs"
on public.flange_thickness_refs
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read b1610 refs" on public.b1610_face_to_face_refs;
create policy "public read b1610 refs"
on public.b1610_face_to_face_refs
for select
to anon, authenticated
using (true);

drop policy if exists "public write b1610 refs" on public.b1610_face_to_face_refs;
create policy "public write b1610 refs"
on public.b1610_face_to_face_refs
for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "public read b1634 refs" on public.b1634_wall_thickness_refs;
create policy "public read b1634 refs"
on public.b1634_wall_thickness_refs
for select
to anon, authenticated
using (true);

drop policy if exists "public write b1634 refs" on public.b1634_wall_thickness_refs;
create policy "public write b1634 refs"
on public.b1634_wall_thickness_refs
for all
to anon, authenticated
using (true)
with check (true);

-- Storage bucket for uploads (public read URLs; same RLS model as tables).
insert into storage.buckets (id, name, public)
values ('valve-attachments', 'valve-attachments', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "valve_attachments storage select" on storage.objects;
create policy "valve_attachments storage select"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'valve-attachments');

drop policy if exists "valve_attachments storage insert" on storage.objects;
create policy "valve_attachments storage insert"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'valve-attachments');

drop policy if exists "valve_attachments storage delete" on storage.objects;
create policy "valve_attachments storage delete"
on storage.objects
for delete
to anon, authenticated
using (bucket_id = 'valve-attachments');

-- ============================================================
-- Traveler Schema Extension
-- ============================================================

create table if not exists public.valve_types (
  id text primary key,
  label text not null,
  sort_order int default 0
);

insert into public.valve_types (id, label, sort_order) values
  ('a', 'Lubricated Plug Valve',                  1),
  ('b', 'Non Lubricated Plug Valve',              2),
  ('c', 'Orbit Valve',                            3),
  ('d', 'Piston Check',                           4),
  ('f', 'Pressure Seal Check Valve',              5),
  ('g', 'Pressure Seal Gate Valve',               6),
  ('h', 'Pressure Seal Globe Valve',              7),
  ('i', 'Twinseal',                               8),
  ('j', 'Pipeline Gate',                          9),
  ('k', 'Angle Globe Valve',                     10),
  ('l', 'Check Valve',                           11),
  ('m', 'Gate Valve',                            12),
  ('n', 'Globe Valve',                           13),
  ('o', 'Ball Valve',                            14),
  ('p', 'Wedge Plug',                            15),
  ('q', 'Delayed Coker - Isolation Ball Valve',  16),
  ('r', 'Relief Valve - VR Traveler',            17),
  ('s', 'Relief Valve - TO Traveler',            18),
  ('t', 'Manufacturing Traveler',                19)
on conflict (id) do nothing;

create table if not exists public.manufacturers (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz default now()
);

create table if not exists public.packing_sizes (
  id uuid primary key default gen_random_uuid(),
  label text not null unique
);

create table if not exists public.test_gauges (
  id uuid primary key default gen_random_uuid(),
  gauge_type text not null,
  gauge_id text not null,
  updated_at timestamptz default now()
);

insert into public.test_gauges (gauge_type, gauge_id) values
  ('Low',     'JS284'),
  ('High',    'JS284'),
  ('Shell',   'JS284'),
  ('Methane', '1'),
  ('Helium',  '304046')
on conflict do nothing;

create table if not exists public.travelers (
  id uuid primary key default gen_random_uuid(),
  valve_id text not null unique,
  valve_type_id text references public.valve_types(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  is_complete boolean default false
);

create index if not exists travelers_valve_id_idx on public.travelers(valve_id);

create table if not exists public.traveler_basic_info (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  customer text,
  salesman text,
  purchase_order_no text,
  customer_valve_id text,
  location_id text,
  manufacturer_id uuid references public.manufacturers(id),
  manufacturer_name text,
  due_date date,
  manufacturer_sn text,
  pressure text,
  size text,
  outlet_connection text check (outlet_connection in ('RF','RTJ','BW','FF','Other')),
  figure_number text,
  drawing_number text,
  operator text check (operator in ('Handwheel','Gear Op.','Air Act.','Electric Act.')),
  valve_condition text check (valve_condition in ('Repairable','Unrepairable')),
  junked_reason text,
  notes text,
  material_id jsonb default '{}'::jsonb,
  pmi_required boolean,
  pmi_attached boolean,
  tech_initials text,
  submitted_at timestamptz,
  is_complete boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.traveler_attachments (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  file_type text not null check (file_type in (
    'image_before',
    'image_after',
    'qa_doc',
    'additional_doc',
    'weld_cert',
    'pmi_report'
  )),
  file_name text not null,
  file_url text not null,
  file_size int,
  uploaded_by text,
  uploaded_at timestamptz default now()
);

create index if not exists traveler_attachments_traveler_id_idx
  on public.traveler_attachments(traveler_id);

create table if not exists public.traveler_valve_selection (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  notes text,
  tech_initials text,
  submitted_at timestamptz,
  is_complete boolean default false,
  is_na boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.traveler_parts (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  part_name text,
  part_number text,
  quantity int default 1,
  unit_cost numeric(10,2),
  status text check (status in ('needed','ordered','received','installed')),
  ordered_date date,
  received_date date,
  supplier text,
  notes text,
  created_at timestamptz default now()
);

create table if not exists public.traveler_valve_specs (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  valve_type_id text references public.valve_types(id),
  kit_type text,
  specs jsonb default '{}'::jsonb,
  tech_initials_specs text,
  submitted_specs_at timestamptz,
  tech_initials_dims text,
  submitted_dims_at timestamptz,
  tech_initials_assembly text,
  submitted_assembly_at timestamptz,
  is_complete boolean default false,
  is_na boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.traveler_welding (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  is_na boolean default false,
  weld_procedure text,
  welder_id text,
  preheat_temp text,
  postheat_temp text,
  filler_material text,
  inspection_result text,
  notes text,
  tech_initials text,
  submitted_at timestamptz,
  is_complete boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.traveler_other_parts (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  is_na boolean default false,
  parts_notes text,
  tech_initials text,
  submitted_at timestamptz,
  is_complete boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.traveler_parts_ordered (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  is_na boolean default false,
  order_notes text,
  tech_initials text,
  submitted_at timestamptz,
  is_complete boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.traveler_testing_qc (
  id uuid primary key default gen_random_uuid(),
  traveler_id uuid not null references public.travelers(id) on delete cascade,
  valve_id text not null,
  testing_notes text,
  testing_tech_initials text,
  testing_completed_at timestamptz,
  qa_test_area_notes text,
  qa_test_area_tech_initials text,
  qa_test_area_completed_at timestamptz,
  shipping_notes text,
  shipping_tech_initials text,
  shipping_completed_at timestamptz,
  final_inspection_notes text,
  final_inspection_tech_initials text,
  final_inspection_completed_at timestamptz,
  is_complete boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.customer_portal_users (
  id uuid primary key default gen_random_uuid(),
  email text not null unique,
  customer_name text not null,
  auth_user_id uuid,
  is_active boolean default true,
  created_at timestamptz default now(),
  last_login_at timestamptz
);

create table if not exists public.inventory (
  id uuid primary key default gen_random_uuid(),
  customer text,
  manufacturer_id uuid references public.manufacturers(id),
  manufacturer_name text,
  valve_type_id text references public.valve_types(id),
  body_material text,
  api_trim text,
  size text,
  pressure text,
  operator text,
  customer_id_no text,
  notes text,
  js_inventory_id text unique,
  origin text,
  image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create or replace function public.traveler_section_status(p_traveler_id uuid)
returns table (
  section text,
  is_complete boolean,
  is_na boolean,
  tech_initials text,
  submitted_at timestamptz
) language sql stable as $$
  select 'basic_info', bi.is_complete, false, bi.tech_initials, bi.submitted_at
    from public.traveler_basic_info bi where bi.traveler_id = p_traveler_id
  union all
  select 'valve_selection', vs.is_complete, vs.is_na, vs.tech_initials, vs.submitted_at
    from public.traveler_valve_selection vs where vs.traveler_id = p_traveler_id
  union all
  select 'valve_specs', sp.is_complete, sp.is_na, sp.tech_initials_assembly, sp.submitted_assembly_at
    from public.traveler_valve_specs sp where sp.traveler_id = p_traveler_id
  union all
  select 'welding', w.is_complete, w.is_na, w.tech_initials, w.submitted_at
    from public.traveler_welding w where w.traveler_id = p_traveler_id
  union all
  select 'other_parts', op.is_complete, op.is_na, op.tech_initials, op.submitted_at
    from public.traveler_other_parts op where op.traveler_id = p_traveler_id
  union all
  select 'parts_ordered', po.is_complete, po.is_na, po.tech_initials, po.submitted_at
    from public.traveler_parts_ordered po where po.traveler_id = p_traveler_id
  union all
  select 'testing_qc', tq.is_complete, false, tq.final_inspection_tech_initials, tq.final_inspection_completed_at
    from public.traveler_testing_qc tq where tq.traveler_id = p_traveler_id;
$$;

create or replace function public.update_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_travelers_updated_at on public.travelers;
create trigger trg_travelers_updated_at
  before update on public.travelers
  for each row execute function public.update_updated_at();

drop trigger if exists trg_basic_info_updated_at on public.traveler_basic_info;
create trigger trg_basic_info_updated_at
  before update on public.traveler_basic_info
  for each row execute function public.update_updated_at();

drop trigger if exists trg_valve_selection_updated_at on public.traveler_valve_selection;
create trigger trg_valve_selection_updated_at
  before update on public.traveler_valve_selection
  for each row execute function public.update_updated_at();

drop trigger if exists trg_valve_specs_updated_at on public.traveler_valve_specs;
create trigger trg_valve_specs_updated_at
  before update on public.traveler_valve_specs
  for each row execute function public.update_updated_at();

drop trigger if exists trg_welding_updated_at on public.traveler_welding;
create trigger trg_welding_updated_at
  before update on public.traveler_welding
  for each row execute function public.update_updated_at();

drop trigger if exists trg_other_parts_updated_at on public.traveler_other_parts;
create trigger trg_other_parts_updated_at
  before update on public.traveler_other_parts
  for each row execute function public.update_updated_at();

drop trigger if exists trg_parts_ordered_updated_at on public.traveler_parts_ordered;
create trigger trg_parts_ordered_updated_at
  before update on public.traveler_parts_ordered
  for each row execute function public.update_updated_at();

drop trigger if exists trg_testing_qc_updated_at on public.traveler_testing_qc;
create trigger trg_testing_qc_updated_at
  before update on public.traveler_testing_qc
  for each row execute function public.update_updated_at();

drop trigger if exists trg_inventory_updated_at on public.inventory;
create trigger trg_inventory_updated_at
  before update on public.inventory
  for each row execute function public.update_updated_at();

alter table public.travelers enable row level security;
alter table public.traveler_basic_info enable row level security;
alter table public.traveler_testing_qc enable row level security;
alter table public.traveler_attachments enable row level security;

drop policy if exists "staff_full_access_travelers" on public.travelers;
create policy "staff_full_access_travelers"
  on public.travelers for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "staff_full_access_basic_info" on public.traveler_basic_info;
create policy "staff_full_access_basic_info"
  on public.traveler_basic_info for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "staff_full_access_testing_qc" on public.traveler_testing_qc;
create policy "staff_full_access_testing_qc"
  on public.traveler_testing_qc for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "staff_full_access_attachments" on public.traveler_attachments;
create policy "staff_full_access_attachments"
  on public.traveler_attachments for all
  to authenticated
  using (true)
  with check (true);

drop policy if exists "customer_read_own_travelers" on public.traveler_basic_info;
create policy "customer_read_own_travelers"
  on public.traveler_basic_info for select
  to authenticated
  using (
    customer = (
      select cpu.customer_name
      from public.customer_portal_users cpu
      where cpu.auth_user_id = auth.uid()
      limit 1
    )
  );

create table if not exists public.valve_type_material_templates (
  valve_type_id text primary key references public.valve_types(id),
  template jsonb not null
);

insert into public.valve_type_material_templates (valve_type_id, template) values
  ('b', '{"body":"","seat":"","diaphragm":"","top_cap":"","thrust_collar":"","metal_diaphragm":"","plug":"","adjuster":""}'),
  ('a', '{"body":"","seat":"","plug":"","top_cap":"","lubricant":""}'),
  ('l', '{"body":"","clapper":"","clapper_nut":"","top_cap":"","seat":"","pin":"","clapper_arm":""}'),
  ('m', '{"body":"","wedge":"","stem":"","seat_rings":"","bonnet":""}'),
  ('n', '{"body":"","disc":"","stem":"","seat_ring":"","bonnet":""}'),
  ('o', '{"body":"","ball":"","stem":"","seats":"","end_caps":""}'),
  ('i', '{"body":"","seats":"","stem":"","end_connections":""}'),
  ('c', '{"body":"","ball":"","stem":"","seats":"","sleeve":""}'),
  ('r', '{"body":"","disc":"","spring":"","nozzle":"","spindle":""}'),
  ('s', '{"body":"","disc":"","spring":"","nozzle":"","spindle":""}')
on conflict (valve_type_id) do nothing;

commit;

-- Attachments: if insert into storage.buckets fails, create bucket "valve-attachments" in Dashboard
-- (public) and re-run only the storage policy block from this file.
--
-- Optional: seed job dropdowns — run supabase/seed-lookup-values.sql once (after lookup_values exists).
-- Optional: seed customers from Excel list — run supabase/seed-customers-from-spreadsheet.sql once.
--
-- Optional: one-time backfill customer list from existing valve rows (run in SQL Editor after customers exists):
-- insert into public.customers (name)
-- select distinct trim(customer) from public.valves
-- where customer is not null and trim(customer) <> ''
-- on conflict (name) do nothing;

-- Optional starter rows:
-- insert into public.valves (valve_id, customer, cell, size, status, due_date) values
-- ('488518-6', 'ABC Refining', 'Finish Cell', '6"', 'Arrived - Not Started', current_date + 2),
-- ('488519-2', 'Pipeline Co', 'Cell 4', '2"', 'Teardown', current_date + 5),
-- ('488520-3', 'West Plant', 'Cell 1', '3"', 'Testing', current_date + 1);
--
-- insert into public.priority_queue (valve_id) values ('488518-6');
