-- Seed customers from Excel “Lists” sheet (run once in Supabase SQL Editor).
insert into public.customers (name) values
  ('ACME'),
  ('AEP Riverside'),
  ('AEP Southwest (Anadarko)'),
  ('AEP Southwest Station'),
  ('AEP/PSO Oologah'),
  ('AEP/PSO TPS'),
  ('AEP/SWEPCO - Flint Creek'),
  ('AG Equipment'),
  ('Allied Power Group (Jim Chamberlin)'),
  ('Caliber Valve & Controls'),
  ('Calpine - Fore River'),
  ('CELEROS'),
  ('CHS'),
  ('Circle B Measurement & Fab'),
  ('City of Coffeyville Power Plant'),
  ('City of Nowata'),
  ('Coffeyville Resources'),
  ('Coffeyville Resources - Pipeline'),
  ('Crane Valves'),
  ('Cross K Construction'),
  ('CVR Nitrogen Plant'),
  ('Edgen Murray'),
  ('Ehtos Energy'),
  ('Enbridge Energy'),
  ('Energy Transfer'),
  ('En-Pro'),
  ('Enterprise Pipeline'),
  ('Explorer Pipeline'),
  ('EXXON Refinery'),
  ('FCX Performrance')
on conflict (name) do nothing;
