-- Seed job dropdown lists (matches Excel defaults). Safe to re-run:
-- on conflict (category, value) do nothing;
insert into public.lookup_values (category, value, sort_order) values
  ('test_type', 'AIR', 0),
  ('test_type', 'AIR / Helium', 1),
  ('test_type', 'Helium Mineral Oil', 2),
  ('test_type', 'Helium Only', 3),
  ('test_type', 'Mineral Oil', 4),
  ('test_type', 'Water', 5),
  ('test_type', 'Water w/ 4 Hour', 6),
  ('test_type', 'Water w/Air', 7),
  ('test_type', 'Water/Helium', 8),
  ('test_type', 'PRV Steam', 9),
  ('test_type', 'PRV Air', 10),
  ('test_type', 'PRV Pretest', 11),
  ('test_type', 'PRV Water', 12),
  ('valve_size', '0.5', 0),
  ('valve_size', '0.75', 1),
  ('valve_size', '1', 2),
  ('valve_size', '1.5', 3),
  ('valve_size', '2', 4),
  ('valve_size', '2.5', 5),
  ('valve_size', '3', 6),
  ('valve_size', '4', 7),
  ('valve_size', '5', 8),
  ('valve_size', '6', 9),
  ('valve_size', '8', 10),
  ('valve_size', '10', 11),
  ('valve_size', '12', 12),
  ('valve_size', '14', 13),
  ('valve_size', '16', 14),
  ('valve_size', '18', 15),
  ('valve_size', '20', 16),
  ('valve_size', '22', 17),
  ('valve_size', '24', 18),
  ('valve_size', '26', 19),
  ('valve_size', '28', 20),
  ('valve_size', '30', 21),
  ('valve_size', '36', 22),
  ('valve_size', '42', 23),
  ('valve_type', '4 WAY Diverter Valve', 0),
  ('valve_type', 'Angle Globe', 1),
  ('valve_type', 'Actuator', 2),
  ('valve_type', 'ARC', 3),
  ('valve_type', 'BALL CHECK', 4),
  ('valve_type', 'Ball Valve', 5),
  ('valve_type', 'BUTTERFLY', 6),
  ('valve_type', 'Check', 7),
  ('valve_type', 'CONTROLVALVE', 8),
  ('valve_type', 'Delayed Coker Switch', 9),
  ('valve_type', 'Delayed Coker Ball', 10),
  ('valve_type', 'DUO CHECK', 11),
  ('valve_type', 'Everlast', 12),
  ('valve_type', 'Gate', 13),
  ('valve_type', 'Globe', 14),
  ('valve_type', 'Knife Gate', 15),
  ('valve_type', 'Lubricated Plug', 16),
  ('valve_type', 'Manufacture/Machine/Weld', 17),
  ('valve_type', 'Mixer', 18),
  ('valve_type', 'MUD VALVE', 19),
  ('valve_type', 'Non Lubricated Plug', 20),
  ('valve_type', 'ORBIT', 21),
  ('valve_type', 'PINCH', 22),
  ('valve_type', 'Pipeline Gate- Slab', 23),
  ('valve_type', 'Pipeline Gate- Expanding', 24),
  ('valve_type', 'Piston Check', 25),
  ('valve_type', 'Pressure Seal Gate', 26),
  ('valve_type', 'Pressure Seal Globe', 27),
  ('valve_type', 'Relief Valve', 28),
  ('valve_type', 'Safety Valve', 29),
  ('valve_type', 'Twinseal', 30),
  ('finish_cell', 'Actuation', 0),
  ('finish_cell', 'Ball Valve', 1),
  ('finish_cell', 'Durco/Twinseal', 2),
  ('finish_cell', 'Field Service', 3),
  ('finish_cell', 'G/G/C', 4),
  ('finish_cell', 'Machine Shop', 5),
  ('finish_cell', 'Pipeline', 6),
  ('finish_cell', 'PRV', 7),
  ('finish_cell', 'Test Only', 8),
  ('finish_cell', 'Welding', 9),
  ('finish_cell', 'Outsourced', 10),
  ('order_type', 'In-Process Order', 0),
  ('order_type', 'Waiting on Arrival', 1),
  ('order_type', 'On-Hold', 2),
  ('order_type', 'Completed', 3)
on conflict (category, value) do nothing;
