-- Run in Supabase SQL Editor to seed the full manufacturer list.
-- Safe to run multiple times (ON CONFLICT DO NOTHING).

insert into public.lookup_values (category, value, sort_order) values
  ('manufacturer', 'ABZ', 1),
  ('manufacturer', 'ADAMS', 2),
  ('manufacturer', 'AG Grobe', 3),
  ('manufacturer', 'All', 4),
  ('manufacturer', 'Alvico', 5),
  ('manufacturer', 'Anderson Greenwood', 6),
  ('manufacturer', 'AIP', 7),
  ('manufacturer', 'ARCO', 8),
  ('manufacturer', 'APOLLO', 9),
  ('manufacturer', 'AquaTrol', 10),
  ('manufacturer', 'ARO', 11),
  ('manufacturer', 'Argus', 12),
  ('manufacturer', 'Artek', 13),
  ('manufacturer', 'ATLAS', 14),
  ('manufacturer', 'ATWOOD & MORRILL', 15),
  ('manufacturer', 'Audco', 16),
  ('manufacturer', 'Baker', 17),
  ('manufacturer', 'Beric', 18),
  ('manufacturer', 'Bonney Forge', 19),
  ('manufacturer', 'Bray', 20),
  ('manufacturer', 'BRON E', 21),
  ('manufacturer', 'Cameron', 22),
  ('manufacturer', 'CAMFLEX', 23),
  ('manufacturer', 'CCI', 24),
  ('manufacturer', 'Chromalox', 25),
  ('manufacturer', 'CHRONISTER', 26),
  ('manufacturer', 'Consolidated', 27),
  ('manufacturer', 'CORAL', 28),
  ('manufacturer', 'COPRES VULCAN', 29),
  ('manufacturer', 'Crane / Pacific', 30),
  ('manufacturer', 'Crosby', 31),
  ('manufacturer', 'CROWN', 32),
  ('manufacturer', 'Danfoss', 33),
  ('manufacturer', 'Daniel', 34),
  ('manufacturer', 'DESCOTE', 35),
  ('manufacturer', 'DGI', 36),
  ('manufacturer', 'DL/SEAL', 37),
  ('manufacturer', 'DURCO', 38),
  ('manufacturer', 'EVERLASTING VALVE CO.', 39),
  ('manufacturer', 'Fairbanks', 40),
  ('manufacturer', 'Farris', 41),
  ('manufacturer', 'Fisher', 42),
  ('manufacturer', 'Flow-Tek', 43),
  ('manufacturer', 'FLOWSEAL', 44),
  ('manufacturer', 'FMC', 45),
  ('manufacturer', 'General', 46),
  ('manufacturer', 'Gheen', 47),
  ('manufacturer', 'Grove', 48),
  ('manufacturer', 'GWC', 49),
  ('manufacturer', 'HAMER JUDD', 50),
  ('manufacturer', 'HANCOCK', 51),
  ('manufacturer', 'Handinger', 52),
  ('manufacturer', 'HP Valves', 53),
  ('manufacturer', 'ISV', 54),
  ('manufacturer', 'JAMESBURY', 55),
  ('manufacturer', 'Keckley', 56),
  ('manufacturer', 'Kitz', 57),
  ('manufacturer', 'KTM', 58),
  ('manufacturer', 'Kunkle', 59),
  ('manufacturer', 'LAT', 60),
  ('manufacturer', 'LECOH', 61),
  ('manufacturer', 'LEIBER', 62),
  ('manufacturer', 'Limburgse', 63),
  ('manufacturer', 'Lurftonheimer', 64),
  ('manufacturer', 'M&M', 65),
  ('manufacturer', 'Mansealon', 66),
  ('manufacturer', 'Neles', 67),
  ('manufacturer', 'Nexus', 68),
  ('manufacturer', 'NGS', 69),
  ('manufacturer', 'Nordstrom', 70),
  ('manufacturer', 'NORSEAL', 71),
  ('manufacturer', 'Norex', 72),
  ('manufacturer', 'OCV', 73),
  ('manufacturer', 'OIC', 74),
  ('manufacturer', 'OMS', 75),
  ('manufacturer', 'OMNI', 76),
  ('manufacturer', 'Orion', 77),
  ('manufacturer', 'OVID', 78),
  ('manufacturer', 'Parker', 79),
  ('manufacturer', 'PK VALVE', 80),
  ('manufacturer', 'Powell', 81),
  ('manufacturer', 'Premier', 82),
  ('manufacturer', 'Prior', 83),
  ('manufacturer', 'PSV', 84),
  ('manufacturer', 'Quadtec', 85),
  ('manufacturer', 'Raymond', 86),
  ('manufacturer', 'REXCO', 87),
  ('manufacturer', 'ROCKWELL EDWARDS', 88),
  ('manufacturer', 'ROCKWELL NORDSTROM', 89),
  ('manufacturer', 'RS', 90),
  ('manufacturer', 'Schafer & Bearing', 91),
  ('manufacturer', 'SCHUBERT TAM', 92),
  ('manufacturer', 'SDV', 93),
  ('manufacturer', 'Sharpe', 94),
  ('manufacturer', 'SIGLA', 95),
  ('manufacturer', 'SITE', 96),
  ('manufacturer', 'SLIDE FLOW', 97),
  ('manufacturer', 'Smith Flow', 98),
  ('manufacturer', 'SMITH 8150', 99),
  ('manufacturer', 'SNYDER SDR', 100),
  ('manufacturer', 'TK', 101),
  ('manufacturer', 'TOE SEAL', 102),
  ('manufacturer', 'Tom Wheeler', 103),
  ('manufacturer', 'Tulsa', 104),
  ('manufacturer', 'Tyco', 105),
  ('manufacturer', 'Valve Technologies', 106),
  ('manufacturer', 'VANAZ-UNO', 107),
  ('manufacturer', 'Varosa', 108),
  ('manufacturer', 'VICO', 109),
  ('manufacturer', 'VIN-LIKE', 110),
  ('manufacturer', 'VINDEO', 111),
  ('manufacturer', 'VM VARGO', 112),
  ('manufacturer', 'VM VOR B13', 113),
  ('manufacturer', 'VMI 116', 114),
  ('manufacturer', 'Vogt', 115),
  ('manufacturer', 'Walworth', 116),
  ('manufacturer', 'WATLOW PLUS', 117),
  ('manufacturer', 'Wheeling', 118),
  ('manufacturer', 'WIL-MAN', 119),
  ('manufacturer', 'WILL MARKS', 120),
  ('manufacturer', 'WISK', 121),
  ('manufacturer', 'Xomox', 122),
  ('manufacturer', 'Yarway', 123),
  ('manufacturer', 'ZIMMERMAN & JANSEN', 124),
  ('manufacturer', 'Other', 125)
on conflict do nothing;
